### ISSUE TITLE
[BUG] download stuck at 99% but failed

### ISSUE THREAD

**Issue by ccinturin** [casualsnek/onthespot#103]
I'm not so into this topic, i'm pretty noob in using pc so i'm just trying to make a djset without paying ALL the tracks. Pls HELPPP!!!

Message: 'Sanitising string: "℗ 2022 Quality Control Music, LLC, under exclusive license to UMG Recordings, Inc."; Allow path separators: False'
Arguments: ()
[2023-11-03 13:10:39,108 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "℗ 2022 Quality Control Music, LLC, under exclusive license to UMG Recordings, Inc."; Allow path separators: False
[2023-11-03 13:10:41,984 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "C:\Users\lenovo\Music\OnTheSpot\Quavo\[2022] Us vs. Them (feat. Gucci Mane)\.~Quavo - Us vs. Them (feat. Gucci Mane) - Us vs. Them (feat. Gucci Mane).ogg"; Allow path separators: True
[2023-11-03 13:10:41,985 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "C:\Users\lenovo\Music\OnTheSpot\Quavo\[2022] Us vs. Them (feat. Gucci Mane)\Quavo - Us vs. Them (feat. Gucci Mane) - Us vs. Them (feat. Gucci Mane).mp3"; Allow path separators: True
[2023-11-03 13:10:41,986 :: spotutils :: utils\spotify.py -> 178:convert_audio_format() :: INFO] -> Converting media with ffmpeg. Built commandline ['ffmpeg.exe', '-i', 'C:\\Users\\lenovo\\Music\\OnTheSpot\\Quavo\\[2022] Us vs. Them (feat. Gucci Mane)\\.~Quavo - Us vs. Them (feat. Gucci Mane) - Us vs. Them (feat. Gucci Mane).ogg', '-ar', '44100', '-ac', '2', '-b:a', '320k', 'C:\\Users\\lenovo\\Music\\OnTheSpot\\Quavo\\[2022] Us vs. Them (feat. Gucci Mane)\\Quavo - Us vs. Them (feat. Gucci Mane) - Us vs. Them (feat. Gucci Mane).mp3']
[2023-11-03 13:10:42,010 :: worker.downloader.SESSION_DL_TH-11af5976-09e4-47e8-bf9b-f7c8fdd449d7 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '6x3gud5JkOSGYJpRUYN1Gg', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 168, in download_track
  File "utils\spotify.py", line 179, in convert_audio_format
  File "subprocess.py", line 408, in check_call
  File "subprocess.py", line 389, in call
  File "subprocess.py", line 1024, in __init__
  File "subprocess.py", line 1509, in _execute_child
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
 !
[2023-11-03 13:10:42,011 :: worker.downloader.SESSION_DL_TH-11af5976-09e4-47e8-bf9b-f7c8fdd449d7 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 6x3gud5JkOSGYJpRUYN1Gg

**System Information (please complete the following information):**
 - OS: [Windows 11]
 - OnTheSpot Version: [e.g. 0.5]

**Comment by casualsnek** [comment]
Are you using onthespot_win_ffm.exe or just onthespot_win.exe ?

**Comment by ccinturin** [comment]
Second one, do i have to use the first?

EDIT: Okay, now I've found the guide on how to run it correctly, tysmmmm!

**Comment by casualsnek** [comment]
> Second one, do i have to use the first?
> 
> EDIT: Okay, now I've found the guide on how to run it correctly, tysmmmm!

Good to know you got it running ! Feel free to create new issues if you face any !

Closing this issue for now !

**Comment by trdahl** [comment]
> Second one, do i have to use the first?
> 
> EDIT: Okay, now I've found the guide on how to run it correctly, tysmmmm!

CAn i see this guide, i get the same error on some files
