### ISSUE TITLE
[BUG] Get metadata failed

### ISSUE THREAD

**Issue by yanon182** [casualsnek/onthespot#109]
**Describe the bug**
Trying to download music results in 30+ percent of songs resulting in ''get metadata failed'' The errors im getting is this (I dont understand any of it lol) 

[2024-01-08 18:45:09,930 :: worker.downloader.SESSION_DL_TH-aff3e257-6c58-4169-921b-b39aa77079a6 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 4dQFrCIfR1HJsesojyMbil
[2024-01-08 18:45:09,931 :: worker.downloader.SESSION_DL_TH-aff3e257-6c58-4169-921b-b39aa77079a6 :: worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '4dQFrCIfR1HJsesojyMbil', Attempt: 1/3
[2024-01-08 18:45:09,932 :: worker.downloader.SESSION_DL_TH-aff3e257-6c58-4169-921b-b39aa77079a6 :: worker\downloader.py -> 97:      download_track() :: ERROR] -> Metadata fetching failed for track by id '4dQFrCIfR1HJsesojyMbil', Traceback (most recent call last):
  File "worker\downloader.py", line 52, in download_track
  File "utils\spotify.py", line 284, in get_song_info
KeyError: 'roleCredits'

Im unsure how to reproduce this error. It just kind of happens when im downloading. I try redownloading and the same songs fail, I close and reopen, restart the pc, even use a vpn and get the same results. I tried on another pc with the same result. 

**Expected behavior**

**Screenshots**
https://gyazo.com/970dc50d1f1b602851150bb8b4b7f069 (Screenshot here if it helps? 

**System Information (please complete the following information):**
 - OS: Windows 10 (Also tested 11) 
 - OnTheSpot Version:  v0.5

**Comment by yanon182** [comment]
Anyone? I cant find a fix anywhere. seems to work fine with other DLers...

**Comment by casualsnek** [comment]
> Anyone? I cant find a fix anywhere. seems to work fine with other DLers...

Working on it.. Can you check if this fixes anything ? https://drive.google.com/file/d/1aXIiR5-iY8OPnkKWr_c5HKBG0KhcHJ0a/view

**Comment by yanon182** [comment]
Seems not, same error and issue. Thanks for getting back to me by the way! I can send the album link of one of the albums giving me an issue if that may help? its many of them but i can send one that might help diagnose?

**Comment by yanon182** [comment]
> > Anyone? I cant find a fix anywhere. seems to work fine with other DLers...
> 
> Working on it.. Can you check if this fixes anything ? https://drive.google.com/file/d/1aXIiR5-iY8OPnkKWr_c5HKBG0KhcHJ0a/view

Seems not, same error and issue. Thanks for getting back to me by the way! I can send the album link of one of the albums giving me an issue if that may help? its many of them but i can send one that might help diagnose?

**Comment by casualsnek** [comment]
> > > Anyone? I cant find a fix anywhere. seems to work fine with other DLers...
> > 
> > 
> > Working on it.. Can you check if this fixes anything ? https://drive.google.com/file/d/1aXIiR5-iY8OPnkKWr_c5HKBG0KhcHJ0a/view
> 
> Seems not, same error and issue. Thanks for getting back to me by the way! I can send the album link of one of the albums giving me an issue if that may help? its many of them but i can send one that might help diagnose?

Sure, link to album for testing would be helpful :)

**Comment by yanon182** [comment]
> > > > Anyone? I cant find a fix anywhere. seems to work fine with other DLers...
> > > 
> > > 
> > > Working on it.. Can you check if this fixes anything ? https://drive.google.com/file/d/1aXIiR5-iY8OPnkKWr_c5HKBG0KhcHJ0a/view
> > 
> > 
> > Seems not, same error and issue. Thanks for getting back to me by the way! I can send the album link of one of the albums giving me an issue if that may help? its many of them but i can send one that might help diagnose?
> 
> Sure, link to album for testing would be helpful :)

Here you go, Give this one a try. If you need more examples just let me know but hopefully whatever fixes this one fixes all the rest. If it does work for you though then maybe its something on my end, but ive tried about everything, including a different pc, a whole different home and internet providor (visited a friend), and even tried using a vpn. Anyways, here ya go! - https://open.spotify.com/album/3A5MgzlDQGfu8TPCPz1g0r?si=l3Xv2XSLQTatzOAmCWh71w

**Comment by casualsnek** [comment]
> > > > > Anyone? I cant find a fix anywhere. seems to work fine with other DLers...
> > > > 
> > > > 
> > > > Working on it.. Can you check if this fixes anything ? https://drive.google.com/file/d/1aXIiR5-iY8OPnkKWr_c5HKBG0KhcHJ0a/view
> > > 
> > > 
> > > Seems not, same error and issue. Thanks for getting back to me by the way! I can send the album link of one of the albums giving me an issue if that may help? its many of them but i can send one that might help diagnose?
> > 
> > 
> > Sure, link to album for testing would be helpful :)
> 
> Here you go, Give this one a try. If you need more examples just let me know but hopefully whatever fixes this one fixes all the rest. If it does work for you though then maybe its something on my end, but ive tried about everything, including a different pc, a whole different home and internet providor (visited a friend), and even tried using a vpn. Anyways, here ya go! - https://open.spotify.com/album/3A5MgzlDQGfu8TPCPz1g0r?si=l3Xv2XSLQTatzOAmCWh71w

Can you try this build ?
https://temp.sh/NCDgB/onthespot_win_ffm.exe

This seems to download the album you linked, at least on my system !

**Comment by yanon182** [comment]
> > > > > > Anyone? I cant find a fix anywhere. seems to work fine with other DLers...
> > > > > 
> > > > > 
> > > > > Working on it.. Can you check if this fixes anything ? https://drive.google.com/file/d/1aXIiR5-iY8OPnkKWr_c5HKBG0KhcHJ0a/view
> > > > 
> > > > 
> > > > Seems not, same error and issue. Thanks for getting back to me by the way! I can send the album link of one of the albums giving me an issue if that may help? its many of them but i can send one that might help diagnose?
> > > 
> > > 
> > > Sure, link to album for testing would be helpful :)
> > 
> > 
> > Here you go, Give this one a try. If you need more examples just let me know but hopefully whatever fixes this one fixes all the rest. If it does work for you though then maybe its something on my end, but ive tried about everything, including a different pc, a whole different home and internet providor (visited a friend), and even tried using a vpn. Anyways, here ya go! - https://open.spotify.com/album/3A5MgzlDQGfu8TPCPz1g0r?si=l3Xv2XSLQTatzOAmCWh71w
> 
> Can you try this build ? https://temp.sh/NCDgB/onthespot_win_ffm.exe
> 
> This seems to download the album you linked, at least on my system !

First off, You are absolutely incredible! It worked flawlessly. I will test some of the other albums i mentioned and get back to you on if they did or didnt work properly. Will leave a good big of downloads going tonight to really give it a deep test drive.  Thank you!

**Comment by yanon182** [comment]
Just giving an update. Every previous album that failed worked great with the new build. I left it downloading around 30 albums from various artists that failed before and each one downloaded without an issue this time. Thanks for the fix! And incase no one tells you this, You are awesome man! Keep up the awesome work!!

**Comment by secto15-byte** [comment]
having this issue as well, can you push a new build? or can you please reupload that link its gone from temp.sh :(. thank you love this app

**Comment by yanon182** [comment]
> having this issue as well, can you push a new build? or can you please reupload that link its gone from temp.sh :(. thank you love this app

If its ok with you and casual, i can send the build casual sent me, But im pretty sure its more of a beta before the new release. Do you have a discord i can send the working one to? delete the post after added (i will do the same for this one)

**Comment by casualsnek** [comment]
> having this issue as well, can you push a new build? or can you please reupload that link its gone from temp.sh :(. thank you love this app

The fixes are already pushed to development branch which you may build yourself.. If you are unable to build try the build i did earlier from here: https://drive.google.com/file/d/1JutlDPKxg9ZLFcdwfiQd5j59viiXiY5j/view

**Comment by Singoleth** [comment]
As of today I get the same issue. I tried your latest build you uploaded above at https://drive.google.com/file/d/1JutlDPKxg9ZLFcdwfiQd5j59viiXiY5j/view, but the issue persists.

Any album I try to download ends in "get metadata failed". I copied and pasted more info here. I am on Windows11. 

[2024-02-27 21:16:54,804 :: worker.downloader.SESSION_DL_TH-b44c5994-3a29-4a47-ace2-325d99c2213c :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 3gMk1HI9r3vjt1tEhnAMWu
[2024-02-27 21:16:54,804 :: worker.downloader.SESSION_DL_TH-b44c5994-3a29-4a47-ace2-325d99c2213c :: worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '3gMk1HI9r3vjt1tEhnAMWu', Attempt: 2/3
[2024-02-27 21:16:54,808 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Jean-Michel Jarre"; Allow path separators: False
[2024-02-27 21:16:54,809 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Electronica 2: The Heart of Noise"; Allow path separators: False
[2024-02-27 21:16:54,809 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "The Heart of Noise, Pt. 2"; Allow path separators: False
[2024-02-27 21:16:54,810 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Columbia"; Allow path separators: False
[2024-02-27 21:16:54,810 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "(P) 2016 Music Affair Entertainment Limited under exclusive license to Sony Music Entertainment Germany GmbH"; Allow path separators: False
[2024-02-27 21:16:54,812 :: worker.downloader.SESSION_DL_TH-b44c5994-3a29-4a47-ace2-325d99c2213c :: worker\downloader.py -> 97:      download_track() :: ERROR] -> Metadata fetching failed for track by id '3gMk1HI9r3vjt1tEhnAMWu', Traceback (most recent call last):
  File "worker\downloader.py", line 66, in download_track
ValueError: Unknown format code 'd' for object of type 'float'

[2024-02-27 21:16:54,813 :: worker.downloader.SESSION_DL_TH-b44c5994-3a29-4a47-ace2-325d99c2213c :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 3gMk1HI9r3vjt1tEhnAMWu

**Comment by yanon182** [comment]
> The Heart of Noise, Pt. 2

Thats odd. I tested this with one of your failed tracks and mine downloaded fine (photo example here - https://gyazo.com/c143fcfc11e6cb3bc629c01bb5264896 ). Hopefully Casualsnek can figure this one out.

**Comment by Singoleth** [comment]
> > The Heart of Noise, Pt. 2
> 
> Thats odd. I tested this with one of your failed tracks and mine downloaded fine (photo example here - https://gyazo.com/c143fcfc11e6cb3bc629c01bb5264896 ). Hopefully Casualsnek can figure this one out.

It is odd. When you tried Casualsnek's new build, did you simply download and double click? Or did you have to remove some of the old installation files?

I get the "get metadata failed" with every download I attempt since a few days ago.

**Comment by yanon182** [comment]
> It is odd. When you tried Casualsnek's new build, did you simply download and double click? Or did you have to remove some of the old installation files?
> 
> I get the "get metadata failed" with every download I attempt since a few days ago.

That is weird. When snek made the updated version i just opened it and it worked instantly and has ever since. im even using it right now. I didnt remove the old version at all. I hope CasualSnek can figure this one out.

**Comment by Singoleth** [comment]
That would be great.

I just tried again and get this error code over and over:

```
[2024-02-28 09:10:00,696 :: worker.downloader.SESSION_DL_TH-b44c5994-3a29-4a47-ace2-325d99c2213c :: worker\downloader.py -> 384:                 run() :: ERROR] -> Download process returned false: 5Bozk731GZkPkaGYP4j32W
[2024-02-28 09:10:00,696 :: worker.downloader.SESSION_DL_TH-b44c5994-3a29-4a47-ace2-325d99c2213c :: worker\downloader.py -> 340:                 run() :: INFO] -> Processing download for track by id '5Bozk731GZkPkaGYP4j32W', Attempt: 2/3
[2024-02-28 09:10:00,698 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Jean-Michel Jarre"; Allow path separators: False
[2024-02-28 09:10:00,698 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Primal Scream"; Allow path separators: False
[2024-02-28 09:10:00,698 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Electronica 2: The Heart of Noise"; Allow path separators: False
[2024-02-28 09:10:00,698 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "As One"; Allow path separators: False
[2024-02-28 09:10:00,699 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Columbia"; Allow path separators: False
[2024-02-28 09:10:00,699 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "(P) 2016 Music Affair Entertainment Limited under exclusive license to Sony Music Entertainment Germany GmbH"; Allow path separators: False
[2024-02-28 09:10:00,700 :: worker.downloader.SESSION_DL_TH-b44c5994-3a29-4a47-ace2-325d99c2213c :: worker\downloader.py -> 97:      download_track() :: ERROR] -> Metadata fetching failed for track by id '5Bozk731GZkPkaGYP4j32W', Traceback (most recent call last):
  File "worker\downloader.py", line 66, in download_track
ValueError: Unknown format code 'd' for object of type 'float'

[2024-02-28 09:10:00,700 :: worker.downloader.SESSION_DL_TH-b44c5994-3a29-4a47-ace2-325d99c2213c :: worker\downloader.py -> 384:                 run() :: ERROR] -> Download process returned false: 5Bozk731GZkPkaGYP4j32W
```

![2024-02-28 09_11_13-casualOnTheSpot](https://github.com/casualsnek/onthespot/assets/161520016/0017362e-eb02-4b55-b440-555ffb6d2e6a)

**Comment by Singoleth** [comment]
@casualsnek I still get the error and can't build myself, unfortunately. Would you share your latest build? Thank you very much.

**Comment by Singoleth** [comment]
I found out what the problem was, I had a special track name formatter that involved track_number. Looks like this metadata is no longer supplied by Spotify. Using {artist} - {name} as track name formatter solved the issue for me. I had to give up track numbers, but it's worth the tradeoff.
