### ISSUE TITLE
[BUG] Nothing in progress bar along with an error

### ISSUE THREAD

**Issue by ghost** [casualsnek/onthespot#110]
**Describe the bug**
I copy and pasted a link to a song and nothing is appearing in the Progress tab

**To Reproduce**
1. Try to download any song
2. Click on 'Progress'
3. Nothings there, infinite 'parsing' 

**Expected behavior**
Song appears in 'Progress' and downloads

**Screenshots**
![image](https://github.com/casualsnek/onthespot/assets/112852330/082bacd5-e9b9-48d1-9519-79a6a64966f7)
![image](https://github.com/casualsnek/onthespot/assets/112852330/75883bef-2f0e-4c7e-8a41-d1528780cd77)

**Error**
```
[2024-01-10 21:28:08,922 :: gui.main_ui :: gui\mainui.py -> 574:__get_search_results() :: INFO] -> Search clicked with value with url https://open.spotify.com/track/4BZlfQdaz59aaFy2lBczm3?si=d8ff472d1a4141c4
[2024-01-10 21:28:08,924 :: gui.main_ui :: gui\mainui.py -> 619:   __download_by_url() :: INFO] -> URL download clicked with value https://open.spotify.com/track/4BZlfQdaz59aaFy2lBczm3?si=d8ff472d1a4141c4
[2024-01-10 21:28:08,925 :: utils :: utils\utils.py -> 125:regex_input_for_urls() :: INFO] -> Parsing url 'https://open.spotify.com/track/4BZlfQdaz59aaFy2lBczm3?si=d8ff472d1a4141c4'
[2024-01-10 21:28:08,932 :: utils :: utils\utils.py -> 222:        get_url_data() :: INFO] -> Parse result for url 'https://open.spotify.com/track/4BZlfQdaz59aaFy2lBczm3?si=d8ff472d1a4141c4'-> track, 4BZlfQdaz59aaFy2lBczm3
[2024-01-10 21:28:08,934 :: gui.main_ui :: gui\mainui.py -> 759:       __send_to_pqp() :: INFO] -> Prepared media for parsing, adding to PQP queue !
[2024-01-10 21:28:08,936 :: gui.main_ui :: gui\mainui.py -> 640:   __download_by_url() :: INFO] -> URL "https://open.spotify.com/track/4BZlfQdaz59aaFy2lBczm3?si=d8ff472d1a4141c4" added to parsing queue
[2024-01-10 21:28:09,226 :: spotutils :: utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Dreamhome"; Allow path separators: False
[2024-01-10 21:28:09,228 :: spotutils :: utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Rosie Ugly"; Allow path separators: False
[2024-01-10 21:28:09,229 :: spotutils :: utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Hotel Pools"; Allow path separators: False
[2024-01-10 21:28:09,230 :: spotutils :: utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Mirrors"; Allow path separators: False
[2024-01-10 21:28:09,231 :: spotutils :: utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Mirrors"; Allow path separators: False
[2024-01-10 21:28:09,233 :: runtimedata :: runtimedata.py -> 49:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "worker\utility.py", line 227, in run
  File "utils\spotify.py", line 318, in get_song_info
KeyError: 'genres'
```

**System Information (please complete the following information):**
 - OS: Windows 10
 - OnTheSpot Version: 0.5

**Additional context**
Before I had some downloads give me a "Get metadata failed" and would keep failing unless I restarted the app.

**Comment by ghost** [comment]
Update, it appears to be 3 songs I can't download, but when I got someone else to download it on their PC, it worked for them.
