### ISSUE TITLE
Download failed !!!

### ISSUE THREAD

**Issue by fusionhost760** [casualsnek/onthespot#116]
!
[2024-03-07 02:34:50,394 :: worker.downloader.SESSION_DL_TH-d18f7e37-18e3-45c8-8fe3-c363c43d0520 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 0FXXvePGfMxgENnXLpBc76
[2024-03-07 02:34:50,395 :: worker.downloader.SESSION_DL_TH-d18f7e37-18e3-45c8-8fe3-c363c43d0520 :: worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '0FXXvePGfMxgENnXLpBc76', Attempt: 2/3
[2024-03-07 02:34:50,661 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Pranay.M. Rijia"; Allow path separators: False
[2024-03-07 02:34:50,662 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Mustafa Zahid"; Allow path separators: False
[2024-03-07 02:34:50,663 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Blood Money (Original Motion Picture Soundtrack)"; Allow path separators: False
[2024-03-07 02:34:50,664 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Teri Yaadon Se"; Allow path separators: False
[2024-03-07 02:34:50,665 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Sony Music Entertainment India Pvt. Ltd."; Allow path separators: False
[2024-03-07 02:34:50,665 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "(P) 2012 Sony Music Entertainment India Pvt. Ltd."; Allow path separators: False
Couldn't extract expiration, invalid parameter in CDN url: https://audio4-gm-fb.spotifycdn.com/audio/a5bcb93a957d854b748e80da770a696ef3136dba?Expires=1709845491~FullPath~hmac=z-SPYhUkcvfVVssIpxHWQykUfyoA1J7qe-ZgPqX8Fps=
[2024-03-07 02:34:51,678 :: worker.downloader.SESSION_DL_TH-d18f7e37-18e3-45c8-8fe3-c363c43d0520 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '0FXXvePGfMxgENnXLpBc76', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 122, in download_track
  File "librespot\audio\__init__.py", line 722, in load
  File "librespot\audio\__init__.py", line 783, in load_track
  File "librespot\audio\__init__.py", line 737, in load_stream
  File "librespot\audio\__init__.py", line 339, in load_track
  File "librespot\audio\__init__.py", line 438, in stream_file
  File "librespot\audio\__init__.py", line 561, in __init__
  File "librespot\audio\__init__.py", line 622, in request
OSError: 404
 !
[2024-03-07 02:34:51,679 :: worker.downloader.SESSION_DL_TH-d18f7e37-18e3-45c8-8fe3-c363c43d0520 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 0FXXvePGfMxgENnXLpBc76

**Comment by El-Nice** [comment]
Do you know if anyone has figured out a solution to the bug ?

**Comment by omarigg04** [comment]
``` bash
TS Version :  0.5
Config version:  0.5
Attempting to use system ffmpeg binary !
Using ffmpeg binary at:  ffmpeg.exe
[2024-08-14 16:39:16,377 :: __init__ :: __init__.py -> 11:                main() :: INFO] -> Starting application in
3
2
1
[2024-08-14 16:39:16,551 :: gui.main_ui :: gui\mainui.py -> 86:            __init__() :: INFO] -> Initialising main window, logging session : 6175b8c4-dc95-46ad-ad73-b151b801c0be
[2024-08-14 16:39:16,566 :: gui.main_ui :: gui\mainui.py -> 102:            __init__() :: INFO] -> Loading configurations..
[2024-08-14 16:39:16,566 :: gui.main_ui :: gui\mainui.py -> 474:      __fill_configs() :: INFO] -> Config filled to UI
[2024-08-14 16:39:16,566 :: gui.main_ui :: gui\mainui.py -> 114:            __init__() :: INFO] -> Preparing session loader
[2024-08-14 16:39:16,582 :: gui.main_ui :: gui\mainui.py -> 126:            __init__() :: INFO] -> Preparing parsing queue processor
[2024-08-14 16:39:16,582 :: worker.session :: worker\session.py -> 17:                 run() :: INFO] -> Session loader has started !
[2024-08-14 16:39:16,582 :: gui.main_ui :: gui\mainui.py -> 170:     set_table_props() :: INFO] -> Setting table item properties
[2024-08-14 16:39:16,582 :: worker.utility :: worker\utility.py -> 90:                 run() :: INFO] -> Parsing queue processor is active !
[2024-08-14 16:39:16,582 :: gui.main_ui :: gui\mainui.py -> 141:            __init__() :: INFO] -> Main window init completed !
[2024-08-14 16:39:16,582 :: worker.utility :: worker\utility.py -> 92:                 run() :: INFO] -> Waiting for new item to parse
[2024-08-14 16:39:16,582 :: gui.main_ui :: gui\mainui.py -> 399:__generate_users_table() :: INFO] -> Accounts table was populated !
[2024-08-14 16:39:33,964 :: gui.main_ui :: gui\mainui.py -> 531:       __add_account() :: INFO] -> Add account clicked
[2024-08-14 16:39:33,965 :: utils :: utils\utils.py -> 50:          login_user() :: INFO] -> logging in user 'gaxi****@****.***'
[2024-08-14 16:39:33,966 :: utils :: utils\utils.py -> 75:          login_user() :: INFO] -> Session file does not exist user 'gaxi****@****.***', attempting login with uname/pass
[2024-08-14 16:39:33,966 :: utils :: utils\utils.py -> 77:          login_user() :: INFO] -> logging in user 'gaxi****@****.***'
[2024-08-14 16:39:35,345 :: utils :: utils\utils.py -> 84:          login_user() :: ERROR] -> Failed logging in user 'gaxi****@****.***', unexpected error !
[2024-08-14 16:39:35,347 :: gui.main_ui :: gui\mainui.py -> 561:       __add_account() :: ERROR] -> Account add failed for : gaxiolaomar04@gmail.com
[2024-08-14 16:39:38,820 :: gui.main_ui :: gui\mainui.py -> 531:       __add_account() :: INFO] -> Add account clicked
[2024-08-14 16:39:38,820 :: gui.main_ui :: gui\mainui.py -> 564:       __add_account() :: INFO] -> Credentials are empty >-<
[2024-08-14 16:40:27,787 :: gui.main_ui :: gui\mainui.py -> 531:       __add_account() :: INFO] -> Add account clicked
[2024-08-14 16:40:27,788 :: utils :: utils\utils.py -> 50:          login_user() :: INFO] -> logging in user '1213****@****.***'
[2024-08-14 16:40:27,788 :: utils :: utils\utils.py -> 75:          login_user() :: INFO] -> Session file does not exist user '1213****@****.***', attempting login with uname/pass
[2024-08-14 16:40:27,789 :: utils :: utils\utils.py -> 77:          login_user() :: INFO] -> logging in user '1213****@****.***'
[2024-08-14 16:40:29,155 :: utils :: utils\utils.py -> 84:          login_user() :: ERROR] -> Failed logging in user '1213****@****.***', unexpected error !
[2024-08-14 16:40:29,156 :: gui.main_ui :: gui\mainui.py -> 561:       __add_account() :: ERROR] -> Account add failed for : 12134171106
[2024-08-14 16:41:01,371 :: gui.main_ui :: gui\mainui.py -> 531:       __add_account() :: INFO] -> Add account clicked
[2024-08-14 16:41:01,372 :: utils :: utils\utils.py -> 50:          login_user() :: INFO] -> logging in user 'gaxi****@****.***'
[2024-08-14 16:41:01,372 :: utils :: utils\utils.py -> 75:          login_user() :: INFO] -> Session file does not exist user 'gaxi****@****.***', attempting login with uname/pass
[2024-08-14 16:41:01,373 :: utils :: utils\utils.py -> 77:          login_user() :: INFO] -> logging in user 'gaxi****@****.***'
[2024-08-14 16:41:02,937 :: utils :: utils\utils.py -> 84:          login_user() :: ERROR] -> Failed logging in user 'gaxi****@****.***', unexpected error !
[2024-08-14 16:41:02,939 :: gui.main_ui :: gui\mainui.py -> 561:       __add_account() :: ERROR] -> Account add failed for : gaxiolaomar04
```
![image](https://github.com/user-attachments/assets/242ea51b-203b-4349-b803-4c499f3c1e95)


I tryed to login with 3 different accounts using mail and username but I wasnt able to access.
@casualsnek This app looks amazing, could you help us to find a solution? 

The best!
