### ISSUE TITLE
ERROR -> Download process returned false: 7H4LlyRX0YjXhJFLN5nIae

### ISSUE THREAD

**Issue by sulaimanusman** [casualsnek/onthespot#119]
C:\Users\Lappytop\onthespot\src>python -m onthespot
OTS Version :  0.5
Config version:  0.5
Attempting to use system ffmpeg binary !
Using ffmpeg binary at:  C:\ffmpeg\bin\ffmpeg.EXE
[2024-03-24 14:11:03,086 :: __init__ :: C:\Users\Lappytop\onthespot\src\onthespot\__init__.py -> 11:                main() :: INFO] -> Starting application in
3
2
1
[2024-03-24 14:11:03,703 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 86:            __init__() :: INFO] -> Initialising main window, logging session : 4113073e-b342-44f7-8176-8b4b32dedd1d
[2024-03-24 14:11:03,734 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 102:            __init__() :: INFO] -> Loading configurations..
[2024-03-24 14:11:03,734 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 474:      __fill_configs() :: INFO] -> Config filled to UI
[2024-03-24 14:11:03,734 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 114:            __init__() :: INFO] -> Preparing session loader
[2024-03-24 14:11:03,734 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 126:            __init__() :: INFO] -> Preparing parsing queue processor
[2024-03-24 14:11:03,734 :: worker.session :: C:\Users\Lappytop\onthespot\src\onthespot\worker\session.py -> 17:                 run() :: INFO] -> Session loader has started !
[2024-03-24 14:11:03,734 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 170:     set_table_props() :: INFO] -> Setting table item properties
[2024-03-24 14:11:03,734 :: worker.session :: C:\Users\Lappytop\onthespot\src\onthespot\worker\session.py -> 23:                 run() :: INFO] -> Trying to create session for musi
[2024-03-24 14:11:03,734 :: worker.utility :: C:\Users\Lappytop\onthespot\src\onthespot\worker\utility.py -> 90:                 run() :: INFO] -> Parsing queue processor is active !
[2024-03-24 14:11:03,734 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 141:            __init__() :: INFO] -> Main window init completed !
[2024-03-24 14:11:03,734 :: worker.utility :: C:\Users\Lappytop\onthespot\src\onthespot\worker\utility.py -> 92:                 run() :: INFO] -> Waiting for new item to parse
[2024-03-24 14:11:03,947 :: utils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\utils.py -> 51:          login_user() :: INFO] -> logging in user 'musi****@****.***'
[2024-03-24 14:11:03,949 :: utils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\utils.py -> 57:          login_user() :: INFO] -> Session file exists for user, attempting to use it 'musi****@****.***'
[2024-03-24 14:11:07,420 :: utils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\utils.py -> 68:          login_user() :: INFO] -> Login successful for user 'musi****@****.***'
[2024-03-24 14:11:07,625 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 399:__generate_users_table() :: INFO] -> Accounts table was populated !
[2024-03-24 14:11:07,682 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 408:   __rebuild_threads() :: INFO] -> Spawning DL thread using session : 5a80c218-9244-41ae-a7bc-7e66f949268e
[2024-03-24 14:11:07,682 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 327:                 run() :: INFO] -> Download worker SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e is running
[2024-03-24 14:11:12,270 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 587:__get_search_results() :: INFO] -> Search clicked with value term alien communication
[2024-03-24 14:11:12,272 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 290:      search_by_term() :: INFO] -> Get search result for term 'alien communication', max items '10'
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
[2024-03-24 14:11:16,813 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 759:       __send_to_pqp() :: INFO] -> Prepared media for parsing, adding to PQP queue !
[2024-03-24 14:11:17,001 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Subtronics"; Allow path separators: False
[2024-03-24 14:11:17,002 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "TESSERACT"; Allow path separators: False
[2024-03-24 14:11:17,003 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Alien Communication"; Allow path separators: False
[2024-03-24 14:11:17,004 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:17,004 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "2024 Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:17,005 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "2024 Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:17,006 :: worker.utility :: C:\Users\Lappytop\onthespot\src\onthespot\worker\utility.py -> 69:      enqueue_tracks() :: INFO] -> PQP parsing Alien Communication:7H4LlyRX0YjXhJFLN5nIae <-> track item: Alien Communication:7H4LlyRX0YjXhJFLN5nIae
[2024-03-24 14:11:17,014 :: worker.utility :: C:\Users\Lappytop\onthespot\src\onthespot\worker\utility.py -> 234:                 run() :: INFO] -> Finished parsing this item !
[2024-03-24 14:11:17,016 :: worker.utility :: C:\Users\Lappytop\onthespot\src\onthespot\worker\utility.py -> 92:                 run() :: INFO] -> Waiting for new item to parse
[2024-03-24 14:11:17,021 :: gui.main_ui :: C:\Users\Lappytop\onthespot\src\onthespot\gui\mainui.py -> 322:__add_item_to_downloads() :: INFO] -> Adding item to download queue -> media_type:track, media_id: 7H4LlyRX0YjXhJFLN5nIae, extra_path:, extra_path_as_root: False, Prefix value: ''
[2024-03-24 14:11:17,022 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '7H4LlyRX0YjXhJFLN5nIae', Attempt: 0/3
[2024-03-24 14:11:17,028 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Subtronics"; Allow path separators: False
[2024-03-24 14:11:17,029 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "TESSERACT"; Allow path separators: False
[2024-03-24 14:11:17,032 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Alien Communication"; Allow path separators: False
[2024-03-24 14:11:17,033 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:17,034 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "2024 Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:17,035 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "2024 Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:19,511 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '7H4LlyRX0YjXhJFLN5nIae', Unexpected error: Traceback (most recent call last):
  File "C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py", line 129, in download_track
    with open(filename, 'wb') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Lappytop\\Music\\OnTheSpot\\Subtronics\\[2024] TESSERACT\\Subtronics - TESSERACT - Alien Communication.mp3'
 !
[2024-03-24 14:11:19,513 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 7H4LlyRX0YjXhJFLN5nIae
[2024-03-24 14:11:19,515 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '7H4LlyRX0YjXhJFLN5nIae', Attempt: 1/3
[2024-03-24 14:11:19,518 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Subtronics"; Allow path separators: False
[2024-03-24 14:11:19,518 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "TESSERACT"; Allow path separators: False
[2024-03-24 14:11:19,519 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Alien Communication"; Allow path separators: False
[2024-03-24 14:11:19,519 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:19,520 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "2024 Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:19,521 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "2024 Cyclops Recordings"; Allow path separators: False
Couldn't extract expiration, invalid parameter in CDN url: https://audio4-gm-fb.spotifycdn.com/audio/e5f55a17f050ca28df41fc67befa1bcee066356e?Expires=1711390281~FullPath~hmac=BNtCGS9POTMFC59aY5zBWNus6I7f4h-eJgtweMDFzAg=
[2024-03-24 14:11:20,858 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '7H4LlyRX0YjXhJFLN5nIae', Unexpected error: Traceback (most recent call last):
  File "C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py", line 122, in download_track
    stream = session.content_feeder().load(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lappytop\AppData\Local\Programs\Python\Python311\Lib\site-packages\librespot\audio\__init__.py", line 722, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lappytop\AppData\Local\Programs\Python\Python311\Lib\site-packages\librespot\audio\__init__.py", line 783, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lappytop\AppData\Local\Programs\Python\Python311\Lib\site-packages\librespot\audio\__init__.py", line 737, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lappytop\AppData\Local\Programs\Python\Python311\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    streamer = session.cdn().stream_file(file, key, url, halt_listener)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lappytop\AppData\Local\Programs\Python\Python311\Lib\site-packages\librespot\audio\__init__.py", line 438, in stream_file
    return CdnManager.Streamer(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lappytop\AppData\Local\Programs\Python\Python311\Lib\site-packages\librespot\audio\__init__.py", line 561, in __init__
    response = self.request(range_start=0,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lappytop\AppData\Local\Programs\Python\Python311\Lib\site-packages\librespot\audio\__init__.py", line 622, in request
    raise IOError(response.status_code)
OSError: 404
 !
[2024-03-24 14:11:20,863 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 7H4LlyRX0YjXhJFLN5nIae
[2024-03-24 14:11:20,865 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '7H4LlyRX0YjXhJFLN5nIae', Attempt: 2/3
[2024-03-24 14:11:21,037 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Subtronics"; Allow path separators: False
[2024-03-24 14:11:21,038 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "TESSERACT"; Allow path separators: False
[2024-03-24 14:11:21,039 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Alien Communication"; Allow path separators: False
[2024-03-24 14:11:21,040 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:21,041 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "2024 Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:21,042 :: spotutils :: C:\Users\Lappytop\onthespot\src\onthespot\utils\spotify.py -> 101:       sanitize_data() :: INFO] -> Sanitising string: "2024 Cyclops Recordings"; Allow path separators: False
[2024-03-24 14:11:22,290 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '7H4LlyRX0YjXhJFLN5nIae', Unexpected error: Traceback (most recent call last):
  File "C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py", line 129, in download_track
    with open(filename, 'wb') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Lappytop\\Music\\OnTheSpot\\Subtronics\\[2024] TESSERACT\\Subtronics - TESSERACT - Alien Communication.mp3'
 !
[2024-03-24 14:11:22,290 :: worker.downloader.SESSION_DL_TH-5a80c218-9244-41ae-a7bc-7e66f949268e :: C:\Users\Lappytop\onthespot\src\onthespot\worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 7H4LlyRX0YjXhJFLN5nIae

**Comment by fatsolko** [comment]
i have the same problem 

```
[2024-04-17 14:13:11,608 :: worker.downloader.SESSION_DL_TH-3da12853-c81b-49e3-ab01-9ab982607e82 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 6VuCBiMrmVZjO3GMZFtMiS
[2024-04-17 14:13:11,609 :: worker.downloader.SESSION_DL_TH-3da12853-c81b-49e3-ab01-9ab982607e82 :: worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '6VuCBiMrmVZjO3GMZFtMiS', Attempt: 1/3
[2024-04-17 14:13:11,611 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "John Maus"; Allow path separators: False
[2024-04-17 14:13:11,611 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Songs"; Allow path separators: False
[2024-04-17 14:13:11,612 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Time To Die"; Allow path separators: False
[2024-04-17 14:13:11,612 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Ribbon Music"; Allow path separators: False
[2024-04-17 14:13:11,612 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2016 Ribbon Music, LLC"; Allow path separators: False
[2024-04-17 14:13:11,613 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2006 Ribbon Music, LLC"; Allow path separators: False
[2024-04-17 14:13:15,140 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "C:\Users\denis\Downloads\Spotify\John Maus\[2006] Songs\.~John Maus - Songs - Time To Die.ogg"; Allow path separators: True
[2024-04-17 14:13:15,140 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "C:\Users\denis\Downloads\Spotify\John Maus\[2006] Songs\John Maus - Songs - Time To Die.mp3"; Allow path separators: True
[2024-04-17 14:13:15,140 :: spotutils :: utils\spotify.py -> 178:convert_audio_format() :: INFO] -> Converting media with ffmpeg. Built commandline ['ffmpeg.exe', '-i', 'C:\\Users\\denis\\Downloads\\Spotify\\John Maus\\[2006] Songs\\.~John Maus - Songs - Time To Die.ogg', '-ar', '44100', '-ac', '2', '-b:a', '320k', 'C:\\Users\\denis\\Downloads\\Spotify\\John Maus\\[2006] Songs\\John Maus - Songs - Time To Die.mp3']
[2024-04-17 14:13:15,147 :: worker.downloader.SESSION_DL_TH-3da12853-c81b-49e3-ab01-9ab982607e82 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '6VuCBiMrmVZjO3GMZFtMiS', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 168, in download_track
  File "utils\spotify.py", line 179, in convert_audio_format
  File "subprocess.py", line 408, in check_call
  File "subprocess.py", line 389, in call
  File "subprocess.py", line 1024, in __init__
  File "subprocess.py", line 1509, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
 !
[2024-04-17 14:13:15,148 :: worker.downloader.SESSION_DL_TH-3da12853-c81b-49e3-ab01-9ab982607e82 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 6VuCBiMrmVZjO3GMZFtMiS
[2024-04-17 14:13:15,148 :: worker.downloader.SESSION_DL_TH-3da12853-c81b-49e3-ab01-9ab982607e82 :: worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '6VuCBiMrmVZjO3GMZFtMiS', Attempt: 2/3
[2024-04-17 14:13:15,291 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "John Maus"; Allow path separators: False
[2024-04-17 14:13:15,291 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Songs"; Allow path separators: False
[2024-04-17 14:13:15,292 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Time To Die"; Allow path separators: False
[2024-04-17 14:13:15,292 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Ribbon Music"; Allow path separators: False
[2024-04-17 14:13:15,292 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2016 Ribbon Music, LLC"; Allow path separators: False
[2024-04-17 14:13:15,293 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2006 Ribbon Music, LLC"; Allow path separators: False
Couldn't extract expiration, invalid parameter in CDN url: https://audio4-gm-fb.spotifycdn.com/audio/540f693d5b4ef29a5af8780d375270c2b7dc00d9?Expires=1713442395~FullPath~hmac=-AbaAxgw83yjhD7gv94Fx-nJqkN1ZTbdEkWj5tlFolk=
[2024-04-17 14:13:16,244 :: worker.downloader.SESSION_DL_TH-3da12853-c81b-49e3-ab01-9ab982607e82 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '6VuCBiMrmVZjO3GMZFtMiS', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 122, in download_track
  File "librespot\audio\__init__.py", line 722, in load
  File "librespot\audio\__init__.py", line 783, in load_track
  File "librespot\audio\__init__.py", line 737, in load_stream
  File "librespot\audio\__init__.py", line 339, in load_track
  File "librespot\audio\__init__.py", line 438, in stream_file
  File "librespot\audio\__init__.py", line 561, in __init__
  File "librespot\audio\__init__.py", line 622, in request
OSError: 404
 !
[2024-04-17 14:13:16,244 :: worker.downloader.SESSION_DL_TH-3da12853-c81b-49e3-ab01-9ab982607e82 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 6VuCBiMrmVZjO3GMZFtMiS
```

**Comment by fatsolko** [comment]
but in raw format everything is ok, i think the error is in convertation from ogg to mp3

**Comment by brunomareque** [comment]
I had the same problem. ogg was downloaded allright, the error was converting to mp3 as @fatsolko said.
In my case i had not ffmpeg on my computer. After you download it, you have to add it to your $PATH and restart.
