### ISSUE TITLE
[BUG] All downloads keep failing

### ISSUE THREAD

**Issue by El-Nice** [casualsnek/onthespot#136]
Hi all the of my downloads are failing 
I tried removing my account and adding it again but its the same
here the log
```
[2024-07-04 20:42:27,490 :: gui.main_ui :: gui\mainui.py -> 574:__get_search_results() :: INFO] -> Search clicked with value with url https://open.spotify.com/track/24oH6Ald0FZtvr7aJJr6sC?si=8a2d10d553bd4745
[2024-07-04 20:42:27,490 :: gui.main_ui :: gui\mainui.py -> 619:   __download_by_url() :: INFO] -> URL download clicked with value https://open.spotify.com/track/24oH6Ald0FZtvr7aJJr6sC?si=8a2d10d553bd4745
[2024-07-04 20:42:27,490 :: utils :: utils\utils.py -> 124:regex_input_for_urls() :: INFO] -> Parsing url 'https://open.spotify.com/track/24oH6Ald0FZtvr7aJJr6sC?si=8a2d10d553bd4745'
[2024-07-04 20:42:27,498 :: utils :: utils\utils.py -> 221:        get_url_data() :: INFO] -> Parse result for url 'https://open.spotify.com/track/24oH6Ald0FZtvr7aJJr6sC?si=8a2d10d553bd4745'-> track, 24oH6Ald0FZtvr7aJJr6sC
[2024-07-04 20:42:27,499 :: gui.main_ui :: gui\mainui.py -> 759:       __send_to_pqp() :: INFO] -> Prepared media for parsing, adding to PQP queue !
[2024-07-04 20:42:27,499 :: gui.main_ui :: gui\mainui.py -> 640:   __download_by_url() :: INFO] -> URL "https://open.spotify.com/track/24oH6Ald0FZtvr7aJJr6sC?si=8a2d10d553bd4745" added to parsing queue
[2024-07-04 20:42:28,680 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Cheb Hichem TGV"; Allow path separators: False
[2024-07-04 20:42:28,681 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Chkoun Li Darli"; Allow path separators: False
[2024-07-04 20:42:28,682 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Chkoun Li Darli"; Allow path separators: False
[2024-07-04 20:42:28,683 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Hichem TGV"; Allow path separators: False
[2024-07-04 20:42:28,685 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2024 Hichem Tgv"; Allow path separators: False
[2024-07-04 20:42:28,686 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2024 Hichem Tgv"; Allow path separators: False
[2024-07-04 20:42:28,687 :: worker.utility :: worker\utility.py -> 69:      enqueue_tracks() :: INFO] -> PQP parsing Chkoun Li Darli:24oH6Ald0FZtvr7aJJr6sC <-> track item: Chkoun Li Darli:24oH6Ald0FZtvr7aJJr6sC
[2024-07-04 20:42:28,712 :: worker.utility :: worker\utility.py -> 246:                 run() :: INFO] -> Finished parsing this item !
[2024-07-04 20:42:28,713 :: worker.utility :: worker\utility.py -> 92:                 run() :: INFO] -> Waiting for new item to parse
[2024-07-04 20:42:28,734 :: gui.main_ui :: gui\mainui.py -> 322:__add_item_to_downloads() :: INFO] -> Adding item to download queue -> media_type:track, media_id: 24oH6Ald0FZtvr7aJJr6sC, extra_path:, extra_path_as_root: False, Prefix value: ''
[2024-07-04 20:42:28,734 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '24oH6Ald0FZtvr7aJJr6sC', Attempt: 0/3
[2024-07-04 20:42:28,746 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Cheb Hichem TGV"; Allow path separators: False
[2024-07-04 20:42:28,752 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Chkoun Li Darli"; Allow path separators: False
[2024-07-04 20:42:28,753 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Chkoun Li Darli"; Allow path separators: False
[2024-07-04 20:42:28,754 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Hichem TGV"; Allow path separators: False
[2024-07-04 20:42:28,756 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2024 Hichem Tgv"; Allow path separators: False
[2024-07-04 20:42:28,757 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2024 Hichem Tgv"; Allow path separators: False
Audio key error, code: 1
Audio key error, code: 1
[2024-07-04 20:42:29,801 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '24oH6Ald0FZtvr7aJJr6sC', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 122, in download_track
  File "librespot\audio\__init__.py", line 722, in load
  File "librespot\audio\__init__.py", line 783, in load_track
  File "librespot\audio\__init__.py", line 737, in load_stream
  File "librespot\audio\__init__.py", line 336, in load_track
  File "librespot\audio\__init__.py", line 277, in get_audio_key
  File "librespot\audio\__init__.py", line 278, in get_audio_key
RuntimeError: Failed fetching audio key! gid: 440b6a70a569454189a72ddd9c76d25e, fileId: 7e9eb77d633461c2fdc5a81dc057235e8bbdf49f
 !
[2024-07-04 20:42:29,801 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 24oH6Ald0FZtvr7aJJr6sC
[2024-07-04 20:42:29,801 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '24oH6Ald0FZtvr7aJJr6sC', Attempt: 1/3
[2024-07-04 20:42:29,809 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Cheb Hichem TGV"; Allow path separators: False
[2024-07-04 20:42:29,809 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Chkoun Li Darli"; Allow path separators: False
[2024-07-04 20:42:29,809 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Chkoun Li Darli"; Allow path separators: False
[2024-07-04 20:42:29,812 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Hichem TGV"; Allow path separators: False
[2024-07-04 20:42:29,812 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2024 Hichem Tgv"; Allow path separators: False
[2024-07-04 20:42:29,812 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2024 Hichem Tgv"; Allow path separators: False
Audio key error, code: 1
Audio key error, code: 1
[2024-07-04 20:42:30,992 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '24oH6Ald0FZtvr7aJJr6sC', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 122, in download_track
  File "librespot\audio\__init__.py", line 722, in load
  File "librespot\audio\__init__.py", line 783, in load_track
  File "librespot\audio\__init__.py", line 737, in load_stream
  File "librespot\audio\__init__.py", line 336, in load_track
  File "librespot\audio\__init__.py", line 277, in get_audio_key
  File "librespot\audio\__init__.py", line 278, in get_audio_key
RuntimeError: Failed fetching audio key! gid: 440b6a70a569454189a72ddd9c76d25e, fileId: 7e9eb77d633461c2fdc5a81dc057235e8bbdf49f
 !
[2024-07-04 20:42:30,992 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 24oH6Ald0FZtvr7aJJr6sC
[2024-07-04 20:42:30,999 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '24oH6Ald0FZtvr7aJJr6sC', Attempt: 2/3
[2024-07-04 20:42:31,001 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Cheb Hichem TGV"; Allow path separators: False
[2024-07-04 20:42:31,001 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Chkoun Li Darli"; Allow path separators: False
[2024-07-04 20:42:31,001 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Chkoun Li Darli"; Allow path separators: False
[2024-07-04 20:42:31,001 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Hichem TGV"; Allow path separators: False
[2024-07-04 20:42:31,001 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2024 Hichem Tgv"; Allow path separators: False
[2024-07-04 20:42:31,001 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2024 Hichem Tgv"; Allow path separators: False
Audio key error, code: 1
Audio key error, code: 1
[2024-07-04 20:42:34,250 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '24oH6Ald0FZtvr7aJJr6sC', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 122, in download_track
  File "librespot\audio\__init__.py", line 722, in load
  File "librespot\audio\__init__.py", line 783, in load_track
  File "librespot\audio\__init__.py", line 737, in load_stream
  File "librespot\audio\__init__.py", line 336, in load_track
  File "librespot\audio\__init__.py", line 277, in get_audio_key
  File "librespot\audio\__init__.py", line 278, in get_audio_key
RuntimeError: Failed fetching audio key! gid: 440b6a70a569454189a72ddd9c76d25e, fileId: 7e9eb77d633461c2fdc5a81dc057235e8bbdf49f
 !
[2024-07-04 20:42:34,250 :: worker.downloader.SESSION_DL_TH-bb4c2804-7135-4de0-ae68-385c56b771f9 :: worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 24oH6Ald0FZtvr7aJJr6sC
``` 
os: Windows 11 pro
onthespot : 0.5

**Comment by Callumari08** [comment]
Got this bug too, The song actually downloads, but it fails when it gets to the "convert" step. Not sure what it's converting the file to, but it works just fine.

**Comment by El-Nice** [comment]
> Got this bug too, The song actually downloads, but it fails when it gets to the "convert" step. Not sure what it's converting the file to, but it works just fine.

mine fail at the downloading step so at 0% it doesn't even start downloading

**Comment by ImThatCuhFR** [comment]
Yo i had the same problem and downloaded the _ffm one and it works not sure why

**Comment by Barshan-Mandal** [comment]
> mine fail at the downloading step so at 0% it doesn't even start downloading

mine too

**Comment by justin025** [comment]
>Hi all the of my downloads are failing...

@El-Nice @Barshan-Mandal is ffmpeg installed on your computer, if not try the _ffm builds

>Got this bug too, The song actually downloads, but it fails when it gets to the "convert" step. Not sure what it's converting the file to, but it works just fine.

@Callumari08 You're issue seems ffmpeg related, do you have the ffplay binary installed and does the issue persist on the _ffm versions

**Comment by El-Nice** [comment]
> > Hi all the of my downloads are failing...
> 
> @El-Nice @Barshan-Mandal is ffmpeg installed on your computer, if not try the _ffm builds
> 
> > Got this bug too, The song actually downloads, but it fails when it gets to the "convert" step. Not sure what it's converting the file to, but it works just fine.
> 
> @Callumari08 You're issue seems ffmpeg related, do you have the ffplay binary installed and does the issue persist on the _ffm versions

yes I do actually have ffmpeg installed and I even tried the _ffm version and it still gives me the same error

**Comment by El-Nice** [comment]
Hi for everyone that has the same issue here, I figured out a way to fix it it should be a DNS-related problem cause when I set my wifi DNS as automatic it fixed the issue by the way, I used the _ffm version

**Comment by El-Nice** [comment]
Hi for everyone that has the same issue here, I figured out a way to fix it it should be a DNS-related problem cause when I set my wifi DNS as automatic it fixed the issue by the way, I used the _ffm version
