### ISSUE TITLE
[BUG] Key Error !

### ISSUE THREAD

**Issue by Bean-alt** [casualsnek/onthespot#140]
**Describe the bug**
I Use release build for windows. Python Key Error hapens with 'genres', 'tracks' and 'name' when i tried to download some song titles. A very few titles aren't affected (about five titles) but most of the titles comes with either of above key errors. i can't try anything after this error, i have to reload the program to retry for another title. i use premium account(idk this matters). i tried both ffm bundled and non bundeld builds. also i tried removing and re logging the account. i tried changing some options in gui but non of these worked for me so far. im not a programing guy but i suspect this is having some problems with getting metadata for song id or having trouble with the site.

**To Reproduce**
1. Try : https://open.spotify.com/track/2I5ij1TxbSFDqQI1Aw42Zd?si=c6813783a7f641f3
2. Try : https://open.spotify.com/track/4FSY456pOwDebYAv5TtytK?si=effcebb0a4c849e4

**Console**
----01----

[2024-07-17 18:43:15,058 :: gui.main_ui :: gui\mainui.py -> 587:__get_search_results() :: INFO] -> Search clicked with value term ru ra
[2024-07-17 18:43:15,071 :: spotutils :: utils\spotify.py -> 247:      search_by_term() :: INFO] -> Get search result for term 'ru ra', max items '10'
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
[2024-07-17 18:43:19,026 :: gui.main_ui :: gui\mainui.py -> 759:       __send_to_pqp() :: INFO] -> Prepared media for parsing, adding to PQP queue !
[2024-07-17 18:43:19,287 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Sanjula himala"; Allow path separators: False
[2024-07-17 18:43:19,287 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Ru Ra"; Allow path separators: False
[2024-07-17 18:43:19,287 :: spotutils :: utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Ru Ra"; Allow path separators: False
[2024-07-17 18:43:19,287 :: runtimedata :: runtimedata.py -> 49:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "worker\utility.py", line 227, in run
  File "utils\spotify.py", line 316, in get_song_info
KeyError: 'genres'

---02---
[2024-07-17 18:54:46,801 :: gui.main_ui :: gui\mainui.py -> 587:__get_search_results() :: INFO] -> Search clicked with value term hithak thibuna
[2024-07-17 18:54:46,803 :: spotutils :: utils\spotify.py -> 247:      search_by_term() :: INFO] -> Get search result for term 'hithak thibuna', max items '10'
  OpenType support missing for "MS Shell Dlg 2", script 20
  OpenType support missing for "Arial", script 20
  OpenType support missing for "MS UI Gothic", script 20
  OpenType support missing for "SimSun", script 20
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
[2024-07-17 18:54:52,497 :: gui.main_ui :: gui\mainui.py -> 759:       __send_to_pqp() :: INFO] -> Prepared media for parsing, adding to PQP queue !
[2024-07-17 18:54:52,680 :: runtimedata :: runtimedata.py -> 49:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "worker\utility.py", line 227, in run
  File "utils\spotify.py", line 295, in get_song_info
KeyError: 'tracks'

**System Information (please complete the following information):**
 - OS: [Windows 10]
 - OnTheSpot Version: [0.5]

**Additional context**
Please look into this if you have time. I can try out build form source.

**Comment by espdav** [comment]
i am having the same error

**Comment by espdav** [comment]
any fix on this?

**Comment by justin025** [comment]
The following build may work, it's from the following PR https://github.com/casualsnek/onthespot/pull/138. Let me know if it works.

https://gofile.io/d/Tw3xp3

**Comment by espdav** [comment]
> The following build may work, it's from the following PR #138. Let me know if it works.
> 
> https://gofile.io/d/Tw3xp3

do you have a windows build? i do not have linux

**Comment by espdav** [comment]
hey mate, how do i install it on Windows? @justin025

**Comment by Bean-alt** [comment]
**Correction**: Only few titles were affected at that time. i was able to download most of other titles. I seem to have tried every one in sequence that affected with this problem. Sorry if I mislead.

@justin025 Thanks for looking into this. I looked at your folk it seems to be the solution but i haven't tried your build yet. i will try it when its merged. thanks again. Btw, Have you tried above example links with new build?.

**Comment by justin025** [comment]
Windows build with all the latest pull requests: https://gofile.io/d/s7YUE2

not sure if it actually fixes the issue.

@Bean-alt I hope casualsnek merges my pr but i wouldn't count on it, he hasn't pushed a commit to this repo in over a year. If in a few months there isn't any activity I may fork the repo to maintain the project if there's still community interest. 

> Btw, Have you tried above example links with new build?.

From what i understand, key errors only occur on windows, my previous link was a linux build. Even on my windows build i haven't experienced key errors, id have to read into your logs further
