### ISSUE TITLE
Login Failed! Probably invalid username or password. [BUG]

### ISSUE THREAD

**Issue by omarigg04** [casualsnek/onthespot#148]
``` bash
TS Version :  0.5
Config version:  0.5
Attempting to use system ffmpeg binary !
Using ffmpeg binary at:  ffmpeg.exe
[2024-08-14 16:39:16,377 :: __init__ :: __init__.py -> 11:                main() :: INFO] -> Starting application in
3
2
1
[2024-08-14 16:39:16,551 :: gui.main_ui :: gui\mainui.py -> 86:            __init__() :: INFO] -> Initialising main window, logging session : 6175b8c4-dc95-46ad-ad73-b151b801c0be
[2024-08-14 16:39:16,566 :: gui.main_ui :: gui\mainui.py -> 102:            __init__() :: INFO] -> Loading configurations..
[2024-08-14 16:39:16,566 :: gui.main_ui :: gui\mainui.py -> 474:      __fill_configs() :: INFO] -> Config filled to UI
[2024-08-14 16:39:16,566 :: gui.main_ui :: gui\mainui.py -> 114:            __init__() :: INFO] -> Preparing session loader
[2024-08-14 16:39:16,582 :: gui.main_ui :: gui\mainui.py -> 126:            __init__() :: INFO] -> Preparing parsing queue processor
[2024-08-14 16:39:16,582 :: worker.session :: worker\session.py -> 17:                 run() :: INFO] -> Session loader has started !
[2024-08-14 16:39:16,582 :: gui.main_ui :: gui\mainui.py -> 170:     set_table_props() :: INFO] -> Setting table item properties
[2024-08-14 16:39:16,582 :: worker.utility :: worker\utility.py -> 90:                 run() :: INFO] -> Parsing queue processor is active !
[2024-08-14 16:39:16,582 :: gui.main_ui :: gui\mainui.py -> 141:            __init__() :: INFO] -> Main window init completed !
[2024-08-14 16:39:16,582 :: worker.utility :: worker\utility.py -> 92:                 run() :: INFO] -> Waiting for new item to parse
[2024-08-14 16:39:16,582 :: gui.main_ui :: gui\mainui.py -> 399:__generate_users_table() :: INFO] -> Accounts table was populated !
[2024-08-14 16:39:33,964 :: gui.main_ui :: gui\mainui.py -> 531:       __add_account() :: INFO] -> Add account clicked
[2024-08-14 16:39:33,965 :: utils :: utils\utils.py -> 50:          login_user() :: INFO] -> logging in user 'gaxi****@****.***'
[2024-08-14 16:39:33,966 :: utils :: utils\utils.py -> 75:          login_user() :: INFO] -> Session file does not exist user 'gaxi****@****.***', attempting login with uname/pass
[2024-08-14 16:39:33,966 :: utils :: utils\utils.py -> 77:          login_user() :: INFO] -> logging in user 'gaxi****@****.***'
[2024-08-14 16:39:35,345 :: utils :: utils\utils.py -> 84:          login_user() :: ERROR] -> Failed logging in user 'gaxi****@****.***', unexpected error !
[2024-08-14 16:39:35,347 :: gui.main_ui :: gui\mainui.py -> 561:       __add_account() :: ERROR] -> Account add failed for : gaxiolaomar04@gmail.com
[2024-08-14 16:39:38,820 :: gui.main_ui :: gui\mainui.py -> 531:       __add_account() :: INFO] -> Add account clicked
[2024-08-14 16:39:38,820 :: gui.main_ui :: gui\mainui.py -> 564:       __add_account() :: INFO] -> Credentials are empty >-<
[2024-08-14 16:40:27,787 :: gui.main_ui :: gui\mainui.py -> 531:       __add_account() :: INFO] -> Add account clicked
[2024-08-14 16:40:27,788 :: utils :: utils\utils.py -> 50:          login_user() :: INFO] -> logging in user '1213****@****.***'
[2024-08-14 16:40:27,788 :: utils :: utils\utils.py -> 75:          login_user() :: INFO] -> Session file does not exist user '1213****@****.***', attempting login with uname/pass
[2024-08-14 16:40:27,789 :: utils :: utils\utils.py -> 77:          login_user() :: INFO] -> logging in user '1213****@****.***'
[2024-08-14 16:40:29,155 :: utils :: utils\utils.py -> 84:          login_user() :: ERROR] -> Failed logging in user '1213****@****.***', unexpected error !
[2024-08-14 16:40:29,156 :: gui.main_ui :: gui\mainui.py -> 561:       __add_account() :: ERROR] -> Account add failed for : 12134171106
[2024-08-14 16:41:01,371 :: gui.main_ui :: gui\mainui.py -> 531:       __add_account() :: INFO] -> Add account clicked
[2024-08-14 16:41:01,372 :: utils :: utils\utils.py -> 50:          login_user() :: INFO] -> logging in user 'gaxi****@****.***'
[2024-08-14 16:41:01,372 :: utils :: utils\utils.py -> 75:          login_user() :: INFO] -> Session file does not exist user 'gaxi****@****.***', attempting login with uname/pass
[2024-08-14 16:41:01,373 :: utils :: utils\utils.py -> 77:          login_user() :: INFO] -> logging in user 'gaxi****@****.***'
[2024-08-14 16:41:02,937 :: utils :: utils\utils.py -> 84:          login_user() :: ERROR] -> Failed logging in user 'gaxi****@****.***', unexpected error !
[2024-08-14 16:41:02,939 :: gui.main_ui :: gui\mainui.py -> 561:       __add_account() :: ERROR] -> Account add failed for : gaxiolaomar04
```
![image](https://github.com/user-attachments/assets/242ea51b-203b-4349-b803-4c499f3c1e95)

I tryed to login with 3 different accounts using mail and username but I wasnt able to access.
@casualsnek This app looks amazing, could you help us to find a solution?

**Comment by myki-b** [comment]
Same issue here. Attempted with different account types (both free and premium), with and without VPN. All the same - cannot authenticate.

**Comment by LeGenDaRy15PT** [comment]
Most people have this problem, especially those who changed their password recently, this is due to a problem that Spotify left the librespot project and since then many people have started to have problems using third-party applications to log in.
I hope they fix this app because it's really good.
You can see more about this subject at this link:
https://github.com/librespot-org/librespot/issues/1308

**Comment by ValentinPintat** [comment]
Same problem here on different windows laptops

**Comment by justin025** [comment]
Temporary fix here https://github.com/casualsnek/onthespot/issues/144#issuecomment-2292409458

**Comment by ValentinPintat** [comment]
Hello,
Thank you for your answer 

I tried to lunch the python code I had this error :
`WARNING:root:Transfer playback from desktop client to librespot-python via Spotify Connect in order to store session
WARNING:zeroconf:Error with socket 744 (('0.0.0.0', 5353))): [WinError 87] Paramètre incorrect
Traceback (most recent call last):
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading     
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 509, in recvfrom
    self._register_with_iocp(conn)
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 709, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] Paramètre incorrect
WARNING:zeroconf:Error with socket 1036 (('127.0.0.1', 5353))): [WinError 87] Paramètre incorrect
Traceback (most recent call last):
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 509, in recvfrom
    self._register_with_iocp(conn)
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 709, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] Paramètre incorrect
WARNING:zeroconf:Error with socket 1032 (('192.168.0.170', 5353))): [WinError 87] Paramètre incorrect
Traceback (most recent call last):
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 509, in recvfrom
    self._register_with_iocp(conn)
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 709, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] Paramètre incorrect
WARNING:root:Grabbed <librespot.core.Session object at 0x00000166663E0860> for valentinpintat
WARNING:root:Session stored in credentials.json. Now you can Ctrl+C
Exception in thread zeroconf-http-server:
Traceback (most recent call last):
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Valentin\Documents\GIT\librespot\.venv\Lib\site-packages\librespot\zeroconf.py", line 267, in run
    self.__worker.submit(anonymous)
  File "C:\Users\Valentin\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')`

I tried to continue the tuto, so i downloaded the app and connect to librespot
It did create a file credential.json but when I replace the file config.json by credential.json I have the same error no account listed.
I tried rename credential.json by config.json I have the same error no account listed.

**Comment by justin025** [comment]
Nooo dont replace your config with credentials. You need to replace .cache/onthespot/sessions/ots_login.json. I might make a video tonight demonstrating.

**Comment by ValentinPintat** [comment]
Ok but config.json was the only file that I found in : C:\Users\Valentin\.cache\casualOnTheSpot\sessions

There was no ots_login.json present in the folder sessions

**Comment by justin025** [comment]
can you tell me what is under accounts in C:\Users\Valentin\\.config\onthespot\config.json. Remove your email address before pasting

**Comment by ValentinPintat** [comment]
Sure :

`{
    "version": 0.5,
    "max_threads": 1,
    "parsing_acc_sn": 1,
    "download_root": "C:\\Users\\Valentin\\Music\\OnTheSpot",
    "download_delay": 5,
    "track_name_formatter": "{artist} - {album} - {name}",
    "album_name_formatter": "test\\",
    "playlist_name_formatter": "MyPlaylists\\{name} by {owner}",
    "playlist_track_force_album_dir": true,
    "watch_bg_for_spotify": false,
    "dl_end_padding_bytes": 167,
    "max_retries": 3,
    "max_search_results": 10,
    "media_format": "mp3",
    "podcast_media_format": "mp3",
    "force_raw": false,
    "force_premium": false,
    "chunk_size": 50000,
    "recoverable_fail_wait_delay": 10,
    "disable_bulk_dl_notices": true,
    "inp_enable_lyrics": false,
    "only_synced_lyrics": false,
    "create_m3u_playlists": false,
    "ffmpeg_args": [],
    "show_search_thumbnails": 1,
    "search_thumb_height": 60,
    "metadata_seperator": ";",
    "accounts": [],
    "_ffmpeg_bin_path": "C:\\Users\\Valentin\\AppData\\Local\\Temp\\_MEI123202\\onthespot\\bin\\ffmpeg\\ffmpeg.exe",
    "_log_file": "C:\\Users\\Valentin\\.cache\\casualOnTheSpot\\logs\\78b4ddeb-4548-4ec1-ad8e-43d9b6f45c13\\onthespot.log",
    "_cache_dir": "C:\\Users\\Valentin\\.cache\\casualOnTheSpot"
}`

I noticed there is a line  "accounts": [] but I don't know how to fill it with my account.
Maybe a link with credential.json ?

**Comment by justin025** [comment]
Grab the entire accounts section and replace it with "accounts": [["EMAIL", true, 1, "a"]], finally move credentials to .cache/onthespot/sessions/ots_login_a.json. Your user will now login, hope this helps

**Comment by LeGenDaRy15PT** [comment]
@justin025 I tested it on my Windows and it's giving me this error that @ValentinPintat is giving me

![image](https://github.com/user-attachments/assets/f51d9f57-fdd3-4b41-9737-c57e185c3320)

```
>>> from librespot.zeroconf import ZeroconfServer
>>> import time
>>> import logging
>>> import pathlib
>>>
>>> zs = ZeroconfServer.Builder().create()
>>> logging.warning("Transfer playback from desktop client to librespot-python via Spotify Connect in order to store session")
WARNING:root:Transfer playback from desktop client to librespot-python via Spotify Connect in order to store session
>>>
>>> while True:
...     time.sleep(1)
WARNING:zeroconf:Error with socket 1036 (('0.0.0.0', 5353))): [WinError 87] O parâmetro está incorreto
Traceback (most recent call last):
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 509, in recvfrom
    self._register_with_iocp(conn)
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 709, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] O parâmetro está incorreto
...     if zs._ZeroconfServer__session:
WARNING:zeroconf:Error with socket 1084 (('127.0.0.1', 5353))): [WinError 87] O parâmetro está incorreto
Traceback (most recent call last):
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 509, in recvfrom
    self._register_with_iocp(conn)
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 709, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] O parâmetro está incorreto
...         logging.warning(f"Grabbed {zs._ZeroconfServer__session} for {zs._ZeroconfServer__session.username()}")
WARNING:zeroconf:Error with socket 1088 (('172.25.160.1', 5353))): [WinError 87] O parâmetro está incorreto
Traceback (most recent call last):
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 509, in recvfrom
    self._register_with_iocp(conn)
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 709, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] O parâmetro está incorreto
...
...         if pathlib.Path("credentials.json").exists():
WARNING:zeroconf:Error with socket 1092 (('192.168.1.232', 5353))): [WinError 87] O parâmetro está incorreto
Traceback (most recent call last):
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 509, in recvfrom
    self._register_with_iocp(conn)
  File "C:\Users\filip\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 709, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] O parâmetro está incorreto
```

**Comment by ValentinPintat** [comment]
> Grab the entire accounts section and replace it with "accounts": [["EMAIL", true, 1, "a"]], finally move credentials to .cache/onthespot/sessions/ots_login_a.json. Your user will now login, hope this helps

I saw that on your other post, I tested it but same issue

**Comment by justin025** [comment]
@josefilipe13 Valentin's script created a credentials.json the error is a little different, i;m not sure whats casuing it at the moment, maybe a vpn, WARNING:zeroconf:Error with socket 1092 (('192.168.1.232', 5353))): [WinError 87] O parâmetro está incorreto seems to be a network error

**Comment by justin025** [comment]
@ValentinPintat Post new config.json

**Comment by ValentinPintat** [comment]
@justin025 
Here is the content of my ots_login_a.json

 `{"username": "v****t", "credentials": "QVFCUz****************************************yejhkc0E=", "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS"}`

And the content of my config.json

`{
    "version": 0.5,
    "max_threads": 1,
    "parsing_acc_sn": 1,
    "download_root": "C:\\Users\\Valentin\\Music\\OnTheSpot",
    "download_delay": 5,
    "track_name_formatter": "{artist} - {album} - {name}",
    "album_name_formatter": "test\\",
    "playlist_name_formatter": "MyPlaylists\\{name} by {owner}",
    "playlist_track_force_album_dir": true,
    "watch_bg_for_spotify": false,
    "dl_end_padding_bytes": 167,
    "max_retries": 3,
    "max_search_results": 10,
    "media_format": "mp3",
    "podcast_media_format": "mp3",
    "force_raw": false,
    "force_premium": false,
    "chunk_size": 50000,
    "recoverable_fail_wait_delay": 10,
    "disable_bulk_dl_notices": true,
    "inp_enable_lyrics": false,
    "only_synced_lyrics": false,
    "create_m3u_playlists": false,
    "ffmpeg_args": [],
    "show_search_thumbnails": 1,
    "search_thumb_height": 60,
    "metadata_seperator": ";",
    "accounts": [
    [
        "EMAIL",
        true,
        1,
        "a"
    ]
],
    "_ffmpeg_bin_path": "C:\\Users\\Valentin\\AppData\\Local\\Temp\\_MEI123202\\onthespot\\bin\\ffmpeg\\ffmpeg.exe",
    "_log_file": "C:\\Users\\Valentin\\.cache\\casualOnTheSpot\\logs\\78b4ddeb-4548-4ec1-ad8e-43d9b6f45c13\\onthespot.log",
    "_cache_dir": "C:\\Users\\Valentin\\.cache\\casualOnTheSpot"
}`

**Comment by justin025** [comment]
@ValentinPintat Did you replace EMAIL in config.json

**Comment by LeGenDaRy15PT** [comment]
@justin025 I also didn't create credentials.json because of this error, and I don't have the VPN connected


![image](https://github.com/user-attachments/assets/1d5e9da9-aa05-4381-933a-2a481e013b6a)
![image](https://github.com/user-attachments/assets/c534d13b-9f5a-4910-820d-bc005dd1d22e)

**Comment by justin025** [comment]
@josefilipe13 I'm not really sure how to help you without giving me your username and password. If you try linux this may help, if you want I can provide steps to install in virtualbox.

**Comment by LeGenDaRy15PT** [comment]
@justin025 If you could do me this favor I would appreciate it so I installed Linux on the VirtualBox

**Comment by justin025** [comment]
@josefilipe13 which distro did you install

**Comment by justin025** [comment]
@josefilipe13 Download from here https://linuxmint.com/edition.php?id=316 and run the iso in virtualbox, let me know when you're done

**Comment by justin025** [comment]
@josefilipe13 Depends on your country, how can i contact you other then github.

**Comment by josefilipe13** [comment]
@justin025 You can add me on discord: legendary15pt

**Comment by ValentinPintat** [comment]
@justin025 I managed to resolve my issue

I modifided the config file of 

C:\Users\Valentin\.config\casualOnTheSpot  by adding the email and placing ots_login_a.json in that folder

and 

not C:\Users\Valentin\.cache\casualOnTheSpot\sessions

**Comment by LeGenDaRy15PT** [comment]
@justin025 managed to solve this problem for me, it actually seems difficult but if you follow his steps well he can get it working again
What we did:
Create the script that @justin025 [Script](https://gist.github.com/g42ftw/b61304497cb19564e89f50197cf4d730) mentioned and copy and paste it into notepad and save test.py
Click twice to open test.py and then run spotify desktop --> connect to a device and there you should find librespot python, click on librespot python and it should create credentials.json on the desktop that you will have to move to
 `C:\Users\(USERNAME)\.cache\casualOnTheSpot\sessions\ots_login_a.json`
You should change the name of credentials.json to ots_login_a.json
Once this is done in the `C:\Users\(USERNAME)\.config\casualOnTheSpot\config.json` folder, you must paste this code in the account part     
```
    "accounts": [
	     [
        "EMAIL",
        true,
        1,
        "a"
    ]]
}
```
Once this is done, just change the "EMAIL" to your email and enter onthespot, which should automatically enter your account.

If you want, you can copy and paste the entire code that I will create into a pastebin config.json
https://pastebin.com/HteD10vh
Video tutorial:
[How to fix Spotify Login](https://www.youtube.com/watch?v=6eQx8c4Z2Dg)
PS: I'm not very good at video editing but this gives you an idea of ​​how to do it.
![image](https://github.com/user-attachments/assets/2501db33-d527-4850-9099-d29eb7f8a698)


Credits to @justin025

**Comment by AndiCee** [comment]
@josefilipe13 thank you, I followed your video and it added my account and works. :)

**Comment by neel-cyber** [comment]
> @justin025 managed to solve this problem for me, it actually seems difficult but if you follow his steps well he can get it working again What we did: Create the script that @justin025 [Script](https://github.com/casualsnek/onthespot/issues/144#issuecomment-2292409458) mentioned and copy and paste it into notepad and save test.py Click twice to open test.py and then run spotify desktop --> connect to a device and there you should find librespot python, click on librespot python and it should create credentials.json on the desktop that you will have to move to C:\Users(USERNAME).cache\casualOnTheSpot\sessions\ots_login_a.json You should change the name of credentials.json to ots_login_a.json Once this is done in the C:\Users\filip.config\casualOnTheSpot\config.json folder, you must paste this code in the account part
> 
> ```
>     "accounts": [
> 	     [
>         "EMAIL",
>         true,
>         1,
>         "a"
>     ]]
> }
> ```
> 
> Once this is done, just change the "EMAIL" to your email and enter onthespot, which should automatically enter your account.
> 
> If you want, you can copy and paste the entire code that I will create into a pastebin config.json https://pastebin.com/HteD10vh Video tutorial: [How to fix Spotify Login](https://www.youtube.com/watch?v=6eQx8c4Z2Dg) PS: I'm not very good at video editing but this gives you an idea of ​​how to do it. ![image](https://private-user-images.githubusercontent.com/127091305/358666146-2501db33-d527-4850-9099-d29eb7f8a698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTM1OTksIm5iZiI6MTcyMzk5MzI5OSwicGF0aCI6Ii8xMjcwOTEzMDUvMzU4NjY2MTQ2LTI1MDFkYjMzLWQ1MjctNDg1MC05MDk5LWQyOWViN2Y4YTY5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxNTAxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDdiYWEwNzhmY2U5MjdmNzI1YmIxOGI0OTZhMWMzMmVlMDhlZjMxMmU2OWU1MzcyM2VlNzRkNmVkYTJmYzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.otG9SdMwZc8b4uNQdqUF35k0Gh3d59c3Qzf3qqe5o5M)
> 
> Credits to @justin025

hey im not able to see it in the spotify connect to a device 
i aint much of a techie help me please

**Comment by neel-cyber** [comment]
> @justin025 managed to solve this problem for me, it actually seems difficult but if you follow his steps well he can get it working again What we did: Create the script that @justin025 [Script](https://github.com/casualsnek/onthespot/issues/144#issuecomment-2292409458) mentioned and copy and paste it into notepad and save test.py Click twice to open test.py and then run spotify desktop --> connect to a device and there you should find librespot python, click on librespot python and it should create credentials.json on the desktop that you will have to move to C:\Users(USERNAME).cache\casualOnTheSpot\sessions\ots_login_a.json You should change the name of credentials.json to ots_login_a.json Once this is done in the C:\Users\filip.config\casualOnTheSpot\config.json folder, you must paste this code in the account part
> 
> ```
>     "accounts": [
> 	     [
>         "EMAIL",
>         true,
>         1,
>         "a"
>     ]]
> }
> ```
> 
> Once this is done, just change the "EMAIL" to your email and enter onthespot, which should automatically enter your account.
> 
> If you want, you can copy and paste the entire code that I will create into a pastebin config.json https://pastebin.com/HteD10vh Video tutorial: [How to fix Spotify Login](https://www.youtube.com/watch?v=6eQx8c4Z2Dg) PS: I'm not very good at video editing but this gives you an idea of ​​how to do it. ![image](https://private-user-images.githubusercontent.com/127091305/358666146-2501db33-d527-4850-9099-d29eb7f8a698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTM1OTksIm5iZiI6MTcyMzk5MzI5OSwicGF0aCI6Ii8xMjcwOTEzMDUvMzU4NjY2MTQ2LTI1MDFkYjMzLWQ1MjctNDg1MC05MDk5LWQyOWViN2Y4YTY5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxNTAxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDdiYWEwNzhmY2U5MjdmNzI1YmIxOGI0OTZhMWMzMmVlMDhlZjMxMmU2OWU1MzcyM2VlNzRkNmVkYTJmYzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.otG9SdMwZc8b4uNQdqUF35k0Gh3d59c3Qzf3qqe5o5M)
> 
> Credits to @justin025

i cant connect to librespot python, it says i have to get premium to do that is it possible to make it work in any way ?

**Comment by LeGenDaRy15PT** [comment]
@neel-cyber In fact I'm not sure if it works on non-premium accounts that I haven't tested yet, as the account I'm using is disposable and was the first one I created, if you want to use premium disposable accounts I posted how to do it at this link:
https://github.com/casualsnek/onthespot/issues/144#issuecomment-2295163595

Did you follow the step by step in the video?

**Comment by kafkauskas** [comment]
I can't seem to be able to create the credentials.json file. Can anyone help?

**Comment by LeGenDaRy15PT** [comment]
@kafkauskas Did you follow all these steps and were unable to create credentials.json?
 https://github.com/casualsnek/onthespot/issues/148#issuecomment-2293903804

**Comment by EverydayHuman** [comment]
> @justin025 managed to solve this problem for me, it actually seems difficult but if you follow his steps well he can get it working again What we did: Create the script that @justin025 [Script](https://gist.github.com/g42ftw/b61304497cb19564e89f50197cf4d730) mentioned and copy and paste it into notepad and save test.py Click twice to open test.py and then run spotify desktop --> connect to a device and there you should find librespot python, click on librespot python and it should create credentials.json on the desktop that you will have to move to `C:\Users\(USERNAME)\.cache\casualOnTheSpot\sessions\ots_login_a.json` You should change the name of credentials.json to ots_login_a.json Once this is done in the `C:\Users\(USERNAME)\.config\casualOnTheSpot\config.json` folder, you must paste this code in the account part
> 
> ```
>     "accounts": [
> 	     [
>         "EMAIL",
>         true,
>         1,
>         "a"
>     ]]
> }
> ```
> 
> Once this is done, just change the "EMAIL" to your email and enter onthespot, which should automatically enter your account.
> 
> If you want, you can copy and paste the entire code that I will create into a pastebin config.json https://pastebin.com/HteD10vh Video tutorial: [How to fix Spotify Login](https://www.youtube.com/watch?v=6eQx8c4Z2Dg) PS: I'm not very good at video editing but this gives you an idea of ​​how to do it. ![image](https://private-user-images.githubusercontent.com/127091305/358666146-2501db33-d527-4850-9099-d29eb7f8a698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODE3NjcsIm5iZiI6MTcyNDM4MTQ2NywicGF0aCI6Ii8xMjcwOTEzMDUvMzU4NjY2MTQ2LTI1MDFkYjMzLWQ1MjctNDg1MC05MDk5LWQyOWViN2Y4YTY5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwMjUxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzU3NThkNzVjNGUzNDI1OTliOGRhOWUyYzFhYzY3YWM4Yzg5NGRkZThkYWNlYjNkZWM1MDA2NjYxYmZkNWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZodVW896a2BPqC14edQmduU3QAtFwt2pOcfnPiBJ7c0)
> 
> Credits to @justin025
spotify requires that i have premium in order to connect to the device 
![image](https://github.com/user-attachments/assets/548b5d72-398f-47c2-9dee-8b9d5e6d8ece)

**Comment by Jonathanm1995** [comment]
I did every steps 
But on open onthespot the cmd open and close and won't load onthespot after doing the fix

**Comment by justin025** [comment]
Fixed login, see https://github.com/casualsnek/onthespot/issues/144#issuecomment-2309179102

**Comment by Jonathanm1995** [comment]
@justin025 
When do you have time to fix that login?
Do I put my email between this: "EMAIL"
In the "  " ?

**Comment by Jonathanm1995** [comment]
@justin025  solve the issue for me trough anydesk 
Thanks alot

**Comment by justin025** [comment]
Windows and macos builds with the new login scheme available here:
https://github.com/justin025/onthespot/releases/tag/v0.6

Virus Scan (on exe):
https://www.virustotal.com/gui/file/bf6ccbe856f4a6ef82aaa8fadef0cec5bcfc8cc8c26da0da60a67762a341a11f

**Comment by spyblog91** [comment]
> Windows and macos builds with the new login scheme available here: https://github.com/justin025/onthespot/releases/tag/v0.6
> 
> Virus Scan (on exe): https://www.virustotal.com/gui/file/bf6ccbe856f4a6ef82aaa8fadef0cec5bcfc8cc8c26da0da60a67762a341a11f

Tested and works flawlessly on windows 11. big shout out to your efforts!!!
Fyi cheers from Poland! 👌

![image](https://github.com/user-attachments/assets/c019c884-a6fd-488d-b4dc-fe3aa6a3faa4)

**Comment by MiauMiez** [comment]
Hey guys, is there anything a normal person without much coding experience can do to get this working again? 
I had problems downloading songs so I installed the newest version. Now I can't add any accounts. The tools is useless now :/

Have a  great day!

**Comment by justin025** [comment]
Download v0.6 linked above and install the spotify desktop app. Click add account in onthespot. Next open devices in the spotify app and select onthespot. The app will restart and should be logged in. 

If this process doesn't work for you please file an issue in my repo and I'll get back to you

**Comment by justin025** [comment]
Fixed login bug for free accounts and other minor things in 0.6.1 https://github.com/justin025/onthespot/releases/latest

**Comment by ficarra1002** [comment]
> Fixed login bug for free accounts and other minor things in 0.6.1 https://github.com/justin025/onthespot/releases/latest

FYI this "fix" requires a premium subscription. Dont bother if you don't want to pay.

**Comment by justin025** [comment]
The fix breaks if you have multiple spotify apps open at the same time, when logging in you can only have the desktop app and onthespot. After login you can have as many instances as you'd like
