### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by sniperpirate** [casualsnek/onthespot#22]
windows 11 -running latest version of app

[2022-10-16 09:29:36,013 :: worker\downloader.py -> 185:      download_track() :: ERROR] -> Download failed for track by id '1zzxoZVylsna2BQB65Ppcb', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 89, in download_track
  File "librespot\audio\__init__.py", line 722, in load
  File "librespot\audio\__init__.py", line 783, in load_track
  File "librespot\audio\__init__.py", line 737, in load_stream
  File "librespot\audio\__init__.py", line 336, in load_track
  File "librespot\audio\__init__.py", line 277, in get_audio_key
  File "librespot\audio\__init__.py", line 278, in get_audio_key
RuntimeError: Failed fetching audio key! gid: 33b5773c30214657865adb553239b18f, fileId: 5acf9e5cc5c6d8bcf4f69e1bbbbd5bbb4034d6d9
 !
[2022-10-16 09:29:36,014 :: worker\downloader.py -> 279:                 run() :: ERROR] -> Download process returned false: 1zzxoZVylsna2BQB65Ppcb

**Comment by bruhimill** [comment]
im having the same issue

**Comment by casualsnek** [comment]
> 
Can you try again or try using different account to see if it works ? I used the ID in your issue report and was able to download 'X Gon Give It To Ya' completely !

**Comment by sniperpirate** [comment]
fixed removed the account and added it back in ... works now
