### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by bruhimill** [casualsnek/onthespot#24]
-> Force raw is disabled for track by id '6kXLq2u5answm56UMbHSoA', media converting and tagging will be done !
[2022-10-20 12:37:38,078 :: /Users/fiancee/onthespot/utils/spotify.py -> 129:convert_audio_format() :: INFO] -> Audiosegment media at '/Users/fiancee/Dennis Smile/[2017] Abomination EP/Dennis Smile - Abomination EP - Abomination.mp3'
/usr/local/lib/python3.10/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
[2022-10-20 12:37:38,095 :: /Users/fiancee/onthespot/worker/downloader.py -> 185:      download_track() :: ERROR] -> Download failed for track by id '6kXLq2u5answm56UMbHSoA', Unexpected error: Traceback (most recent call last):
  File "/Users/fiancee/onthespot/worker/downloader.py", line 133, in download_track
    convert_audio_format(filename, quality)
  File "/Users/fiancee/onthespot/utils/spotify.py", line 131, in convert_audio_format
    raw_audio = AudioSegment.from_file(os.path.abspath(filename), format="ogg",
  File "/usr/local/lib/python3.10/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/usr/local/lib/python3.10/site-packages/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
 !
[2022-10-20 12:37:38,097 :: /Users/fiancee/onthespot/worker/downloader.py -> 279:                 run() :: ERROR] -> Download process returned false: 6kXLq2u5answm56UMbHSoA
[2022-10-20 12:37:38,097 :: /Users/fiancee/onthespot/worker/downloader.py -> 248:                 run() :: INFO] -> Processing download for track by id '6kXLq2u5answm56UMbHSoA', Attempt: 1
[2022-10-20 12:37:43,890 :: /Users/fiancee/onthespot/worker/downloader.py -> 128:      download_track() :: WARNING] -> Force raw is disabled for track by id '6kXLq2u5answm56UMbHSoA', media converting and tagging will be done !
[2022-10-20 12:37:43,891 :: /Users/fiancee/onthespot/utils/spotify.py -> 129:convert_audio_format() :: INFO] -> Audiosegment media at '/Users/fiancee/Dennis Smile/[2017] Abomination EP/Dennis Smile - Abomination EP - Abomination.mp3'
/usr/local/lib/python3.10/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
[2022-10-20 12:37:43,903 :: /Users/fiancee/onthespot/worker/downloader.py -> 185:      download_track() :: ERROR] -> Download failed for track by id '6kXLq2u5answm56UMbHSoA', Unexpected error: Traceback (most recent call last):
  File "/Users/fiancee/onthespot/worker/downloader.py", line 133, in download_track
    convert_audio_format(filename, quality)
  File "/Users/fiancee/onthespot/utils/spotify.py", line 131, in convert_audio_format
    raw_audio = AudioSegment.from_file(os.path.abspath(filename), format="ogg",
  File "/usr/local/lib/python3.10/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/usr/local/lib/python3.10/site-packages/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
 !
[2022-10-20 12:37:43,905 :: /Users/fiancee/onthespot/worker/downloader.py -> 279:                 run() :: ERROR] -> Download process returned false: 6kXLq2u5answm56UMbHSoA
[2022-10-20 12:37:43,906 :: /Users/fiancee/onthespot/worker/downloader.py -> 248:                 run() :: INFO] -> Processing download for track by id '6kXLq2u5answm56UMbHSoA', Attempt: 2
[2022-10-20 12:37:49,335 :: /Users/fiancee/onthespot/worker/downloader.py -> 128:      download_track() :: WARNING] -> Force raw is disabled for track by id '6kXLq2u5answm56UMbHSoA', media converting and tagging will be done !
[2022-10-20 12:37:49,335 :: /Users/fiancee/onthespot/utils/spotify.py -> 129:convert_audio_format() :: INFO] -> Audiosegment media at '/Users/fiancee/Dennis Smile/[2017] Abomination EP/Dennis Smile - Abomination EP - Abomination.mp3'
/usr/local/lib/python3.10/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
[2022-10-20 12:37:49,348 :: /Users/fiancee/onthespot/worker/downloader.py -> 185:      download_track() :: ERROR] -> Download failed for track by id '6kXLq2u5answm56UMbHSoA', Unexpected error: Traceback (most recent call last):
  File "/Users/fiancee/onthespot/worker/downloader.py", line 133, in download_track
    convert_audio_format(filename, quality)
  File "/Users/fiancee/onthespot/utils/spotify.py", line 131, in convert_audio_format
    raw_audio = AudioSegment.from_file(os.path.abspath(filename), format="ogg",
  File "/usr/local/lib/python3.10/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/usr/local/lib/python3.10/site-packages/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
 !
[2022-10-20 12:37:49,351 :: /Users/fiancee/onthespot/worker/downloader.py -> 279:                 run() :: ERROR] -> Download process returned false: 6kXLq2u5answm56UMbHSoA

I tried removing and adding in my acc bit to no avail

**Comment by casualsnek** [comment]
From the logs it looks like ffprobe is missing !
If you are running from source you should have ffprobe and ffmpeg binaries on your PATH or you can use ffmpeg embedded binary 'onthespot_win_ffm.exe' from latest release !

**Comment by francobramucci** [comment]
sudo apt install ffmpeg
to solve that issue

**Comment by casualsnek** [comment]
The dependency to Pydub is now removed in development branch ! Can you try installing ffmpeg and see if downloads work properly ?
