### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by shimdidly** [casualsnek/onthespot#3]
I get this error message:

`Traceback (most recent call last):
  File "/home/computer/Downloads/onethespot/onthespot.py", line 3, in <module>
    from config import config
  File "/home/computer/Downloads/onethespot/config.py", line 61, in <module>
    config = Config()
  File "/home/computer/Downloads/onethespot/config.py", line 37, in __init__
    os.makedirs(os.path.dirname(self.get("dlid_cache")), exist_ok=True)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Comment by kinoosaki** [comment]
Same

**Comment by casualsnek** [comment]
This should be fixed in latest commit. Can you try that ?

**Comment by shimdidly** [comment]
Can confirm latest commit resolves this issue for me.

**Comment by kinoosaki** [comment]
> This should be fixed in latest commit. Can you try that ?

wait a sec lemme see

**Comment by kinoosaki** [comment]
works now
