### ISSUE TITLE
Thumbnail error on anthing but mp3.

### ISSUE THREAD

**Issue by SuperTort0ise** [casualsnek/onthespot#31]
When downloading with media format set to anything but mp3 i get this error: 
[2022-11-11 00:26:13,213 :: worker/downloader.py -> 185: download_track() :: ERROR] -> Download failed for track by id '0CL7VjsK7XnkDqoFU6eTMD', Unexpected error: Traceback (most recent call last):
  File "worker/downloader.py", line 138, in download_track
  File "utils/spotify.py", line 170, in set_music_thumbnail
  File "music_tag/file.py", line 603, in __setitem__
  File "music_tag/file.py", line 503, in set
  File "music_tag/vorbis.py", line 41, in set_pictures
ImportError: Please install Pillow to properly handle images !
[2022-11-11 00:26:13,213 :: worker/downloader.py -> 279: run() :: ERROR] -> Download process returned false: 0CL7VjsK7XnkDqoFU6eTMD

Pillow is installed and mp3 works fine, I'm on Arch Linux installed from AUR.

I know I shouldn't make a suggestion on an issue but it'd be cool to have a ffmpeg args/bitrate field. Thanks.

**Comment by casualsnek** [comment]
The issue should be fixed now, as pillow is packaged too if you were using binary packages ! For the bitrate setting ! The latest version from development branch should add a new ffmmpeg_args field in config file where you could add any other arguments that gets passed to ffmpeg !

**Comment by SuperTort0ise** [comment]
Just tested dev and it's perfect.
This is legit the best app for downloading songs from Spotify, fast easy and really configurable, I love that it's qt too. <3
