### ISSUE TITLE
Download Error - No such file or directory

### ISSUE THREAD

**Issue by lavolp3** [casualsnek/onthespot#45]
I get errors trying to download a specific german audio series as seen below. 
However, when I save the files using the formatter  {artist}\{album} instead of standard {artist}\[{rel_year}] {album} 
the downloads do work

Working on windows 11 with administrator rights and wiht the latest .exe release

```
[2023-01-26 21:24:05,978 :: worker\downloader.py -> 248:                 run() :: INFO] -> Processing download for track by id '35FjLFs9vqxdcuhXR9tGa8', Attempt: 2
[2023-01-26 21:24:06,292 :: worker\downloader.py -> 185:      download_track() :: ERROR] -> Download failed for track by id '35FjLFs9vqxdcuhXR9tGa8', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 96, in download_track
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dirk\\Music\\OnTheSpot\\Robin Hood - Schlitzohr von Sherwood\\[2014] Folge 1 Die Schatzkiste (Das Original-Hörspiel zur TV-Serie)\\Robin Hood - Schlitzohr von Sherwood - Folge 1 Die Schatzkiste (Das Original-Hörspiel zur TV-Serie) - Die Entführung - Teil 1.mp3'
 !
[2023-01-26 21:24:06,308 :: worker\downloader.py -> 279:                 run() :: ERROR] -> Download process returned false: 35FjLFs9vqxdcuhXR9tGa8
```

**Comment by casualsnek** [comment]
This should be fixed on latest development branch, can you give it a try and see if the issue is fixed ?

**Comment by macxdd** [comment]
I guess the issue creator is not gonna give feedback, but I've started use the program today, I'm using the development branch, and I'm getting a similar error when I try to download playlists:

FileNotFoundError: [WinError 2] The system cannot find the file specified
 !
[2023-07-27 19:08:13,858 :: worker.downloader.SESSION_DL_TH-ff138f85-224b-48c0-9a55-f51ed1711e77 :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\worker\downloader.py -> 385:                 run() :: ERROR] -> Download process returned false: 02VBYrHfVwfEWXk5DXyf0T
[2023-07-27 19:08:18,862 :: worker.downloader.SESSION_DL_TH-ff138f85-224b-48c0-9a55-f51ed1711e77 :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\worker\downloader.py -> 341:                 run() :: INFO] -> Processing download for track by id '4SvhIfAl0nqli7X20A7YtA', Attempt: 0/1
[2023-07-27 19:08:19,038 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Aaron Taylor"; Allow path separators: False
[2023-07-27 19:08:19,039 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "The Long Way Home"; Allow path separators: False
[2023-07-27 19:08:19,041 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "I Think I Love You Again"; Allow path separators: False
[2023-07-27 19:08:19,042 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "Edenic Records"; Allow path separators: False
[2023-07-27 19:08:19,043 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2018 Edenic Records"; Allow path separators: False
[2023-07-27 19:08:19,043 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "2018 Edenic Records"; Allow path separators: False
[2023-07-27 19:08:22,056 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "D:\CMD 4a\songss\Aaron Taylor [2018] The Long Way Home\.~Aaron Taylor - The Long Way Home - I Think I Love You Again.ogg"; Allow path separators: True
[2023-07-27 19:08:22,057 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 97:       sanitize_data() :: INFO] -> Sanitising string: "D:\CMD 4a\songss\Aaron Taylor [2018] The Long Way Home\Aaron Taylor - The Long Way Home - I Think I Love You Again.mp3"; Allow path separators: True
[2023-07-27 19:08:22,059 :: spotutils :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py -> 178:convert_audio_format() :: INFO] -> Converting media with ffmpeg. Built commandline ['ffmpeg.exe', '-i', 'D:\\CMD 4a\\songss\\Aaron Taylor [2018] The Long Way Home\\.~Aaron Taylor - The Long Way Home - I Think I Love You Again.ogg', '-ar', '44100', '-ac', '2', '-b:a', '320k', 'D:\\CMD 4a\\songss\\Aaron Taylor [2018] The Long Way Home\\Aaron Taylor - The Long Way Home - I Think I Love You Again.mp3']
[2023-07-27 19:08:22,123 :: worker.downloader.SESSION_DL_TH-ff138f85-224b-48c0-9a55-f51ed1711e77 :: C:\Users\malpe\Desktop\onthespot-development\src\onthespot\worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '4SvhIfAl0nqli7X20A7YtA', Unexpected error: Traceback (most recent call last):
  File "C:\Users\malpe\Desktop\onthespot-development\src\onthespot\worker\downloader.py", line 168, in download_track
    convert_audio_format(filename, quality)
  File "C:\Users\malpe\Desktop\onthespot-development\src\onthespot\utils\spotify.py", line 179, in convert_audio_format
    subprocess.check_call(command, shell=False)
  File "C:\Users\malpe\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malpe\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malpe\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\malpe\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by macxdd** [comment]
I had missed instructions were different for development branch. I've got it running after doing ffmpeg thingies. 

So, basically it's working. Thank you so much!
