### ISSUE TITLE
Some songs fail at 99%

### ISSUE THREAD

**Issue by ghost** [casualsnek/onthespot#62]
I'm using the latest developmentBranch build and some songs fail at 99%

[2023-05-20 01:52:09,075 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '44UnT7KIVgEQFkUeXUp3OJ', Unexpected error: Traceback (most recent call last):
  File "PIL\PngImagePlugin.py", line 1286, in _save
KeyError: 'CMYK'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "worker\downloader.py", line 172, in download_track
  File "utils\spotify.py", line 203, in set_music_thumbnail
  File "PIL\Image.py", line 2432, in save
  File "PIL\PngImagePlugin.py", line 1289, in _save
OSError: cannot write mode CMYK as PNG
 !
[2023-05-20 01:52:09,082 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 377:                 run() :: ERROR] -> Download process returned false: 44UnT7KIVgEQFkUeXUp3OJ

![image](https://github.com/casualsnek/onthespot/assets/45408242/670afa96-d4fe-4713-b374-8d64c3f8e862)

**Comment by casualsnek** [comment]
> I'm using the latest developmentBranch build and some songs fail at 99%
> 
> [2023-05-20 01:52:09,075 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 222: download_track() :: ERROR] -> Download failed for track by id '44UnT7KIVgEQFkUeXUp3OJ', Unexpected error: Traceback (most recent call last): File "PIL\PngImagePlugin.py", line 1286, in _save KeyError: 'CMYK'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "worker\downloader.py", line 172, in download_track File "utils\spotify.py", line 203, in set_music_thumbnail File "PIL\Image.py", line 2432, in save File "PIL\PngImagePlugin.py", line 1289, in _save OSError: cannot write mode CMYK as PNG ! [2023-05-20 01:52:09,082 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 377: run() :: ERROR] -> Download process returned false: 44UnT7KIVgEQFkUeXUp3OJ
> 
> ![image](https://user-images.githubusercontent.com/45408242/239590989-670afa96-d4fe-4713-b374-8d64c3f8e862.png)

Just pushed https://github.com/casualsnek/onthespot/commit/3d10727edf91edf4d235857ba6ca1e48993d2969 can you pull the latest development branch and see if it's working now ?

**Comment by ghost** [comment]
It worked.
thank you.
