### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by ghost** [casualsnek/onthespot#63]
If the song name contains ":", the download will fail.
use development branch

`[2023-05-20 08:20:30,035 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 333:                 run() :: INFO] -> Processing download for track by id '1fipeXkeQo8nXoWU2Rbu29', Attempt: 2/3
[2023-05-20 08:20:32,085 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '1fipeXkeQo8nXoWU2Rbu29', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 168, in download_track
  File "utils\spotify.py", line 138, in convert_audio_format
OSError: [WinError 87] パラメーターが間違っています。: 'C:\\Users\\username\\Music\\OnTheSpot\\Yukari Tamura\\螺旋の果実\\15 - W:Wonder tale.mp3' -> 'C:\\Users\\username\\Music\\OnTheSpot\\Yukari Tamura\\螺旋の果実\\.~15 - W:Wonder tale.ogg'
 !
[2023-05-20 08:20:32,086 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 377:                 run() :: ERROR] -> Download process returned false: 1fipeXkeQo8nXoWU2Rbu29`

**Comment by sakuraimikoto33** [comment]
use development branch

**Comment by ghost** [comment]
Similar error with another song

`[2023-05-20 13:38:54,165 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 333:                 run() :: INFO] -> Processing download for track by id '1fPWFs6GjcSXknQKa6YKIh', Attempt: 2/3
[2023-05-20 13:38:54,774 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 222:      download_track() :: ERROR] -> Download failed for track by id '1fPWFs6GjcSXknQKa6YKIh', Unexpected error: Traceback (most recent call last):
  File "worker\downloader.py", line 124, in download_track
  File "os.py", line 225, in makedirs
NotADirectoryError: [WinError 267] ディレクトリ名が無効です。: 'C:\\Users\\username\\Music\\OnTheSpot\\Marty Friedman\\B: The Beginning THE IMAGE ALBUM'
 !
[2023-05-20 13:38:54,775 :: worker.downloader.SESSION_DL_TH-810c87d7-4119-4e36-9b93-93722a94d6f8 :: worker\downloader.py -> 377:                 run() :: ERROR] -> Download process returned false: 1fPWFs6GjcSXknQKa6YKIh`

**Comment by casualsnek** [comment]
Can yo try development branch again ? It should be fixed now !

**Comment by ghost** [comment]
It worked
thank you
