### ISSUE TITLE
Playlist creation error

### ISSUE THREAD

**Issue by ghost** [casualsnek/onthespot#64]
Playlist creation fails if the playlist name contains "/".
https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk

`[2023-05-21 23:48:01,083 :: worker.utility :: worker\utility.py -> 26:                 run() :: INFO] -> Playlist m3u8 checking ID 2KC9BMH2fMqKbGcHV2lwwk
[2023-05-21 23:48:01,083 :: worker.utility :: worker\utility.py -> 31:                 run() :: INFO] -> Playlist 2KC9BMH2fMqKbGcHV2lwwk has all items ready, making m3u8 playlist at: {play_queue[play_id]["filename"]}!
[2023-05-21 23:48:01,084 :: runtimedata :: runtimedata.py -> 51:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "worker\utility.py", line 35, in run
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\Music\\OnTheSpot\\!Playlist\\2007年-2023年 VOCALOID 伝説入り・神話入り楽曲 \\ 100万回再生超え ボカロ.m3u8'`

Use latest development branch

**Comment by casualsnek** [comment]
Looks like i the filenames were not sanitized properly:
Windows does not allow following characters in filenames
<,>,:,",/,\,|,?,*

I'll fix it asap !

**Comment by casualsnek** [comment]
This should be now fixed in development branch !

**Comment by ghost** [comment]
An error occurs when trying to download a playlist.

Previously, songs were added to Progress.
But now I get an error before it's added to Progress.

`[2023-05-23 20:07:51,966 :: gui.main_ui :: gui\mainui.py -> 574:__get_search_results() :: INFO] -> Search clicked with value with url https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk?si=6e1787acc3884ef7
[2023-05-23 20:07:51,967 :: gui.main_ui :: gui\mainui.py -> 619:   __download_by_url() :: INFO] -> URL download clicked with value https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk?si=6e1787acc3884ef7
[2023-05-23 20:07:51,967 :: utils :: utils\utils.py -> 124:regex_input_for_urls() :: INFO] -> Parsing url 'https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk?si=6e1787acc3884ef7'
[2023-05-23 20:07:51,968 :: utils :: utils\utils.py -> 227:        get_url_data() :: INFO] -> Parse result for url 'https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk?si=6e1787acc3884ef7'-> playlist, 2KC9BMH2fMqKbGcHV2lwwk
[2023-05-23 20:07:51,977 :: spotutils :: utils\spotify.py -> 28:   get_playlist_data() :: INFO] -> Get playlist dump for '2KC9BMH2fMqKbGcHV2lwwk'
[2023-05-23 20:07:52,434 :: runtimedata :: runtimedata.py -> 51:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "worker\utility.py", line 192, in run
  File "utils\spotify.py", line 31, in get_playlist_data
  File "utils\spotify.py", line 84, in sanitize_data
AttributeError: 'dict' object has no attribute 'replace'`

**Comment by casualsnek** [comment]
> An error occurs when trying to download a playlist.
> 
> Previously, songs were added to Progress. But now I get an error before it's added to Progress.
> 
> `[2023-05-23 20:07:51,966 :: gui.main_ui :: gui\mainui.py -> 574:__get_search_results() :: INFO] -> Search clicked with value with url https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk?si=6e1787acc3884ef7 [2023-05-23 20:07:51,967 :: gui.main_ui :: gui\mainui.py -> 619: __download_by_url() :: INFO] -> URL download clicked with value https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk?si=6e1787acc3884ef7 [2023-05-23 20:07:51,967 :: utils :: utils\utils.py -> 124:regex_input_for_urls() :: INFO] -> Parsing url 'https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk?si=6e1787acc3884ef7' [2023-05-23 20:07:51,968 :: utils :: utils\utils.py -> 227: get_url_data() :: INFO] -> Parse result for url 'https://open.spotify.com/playlist/2KC9BMH2fMqKbGcHV2lwwk?si=6e1787acc3884ef7'-> playlist, 2KC9BMH2fMqKbGcHV2lwwk [2023-05-23 20:07:51,977 :: spotutils :: utils\spotify.py -> 28: get_playlist_data() :: INFO] -> Get playlist dump for '2KC9BMH2fMqKbGcHV2lwwk' [2023-05-23 20:07:52,434 :: runtimedata :: runtimedata.py -> 51: handle_exception() :: CRITICAL] -> Uncaught exception Traceback (most recent call last): File "worker\utility.py", line 192, in run File "utils\spotify.py", line 31, in get_playlist_data File "utils\spotify.py", line 84, in sanitize_data AttributeError: 'dict' object has no attribute 'replace'`

Should be fixed now !

**Comment by ghost** [comment]
It worked!
thank you
