### ISSUE TITLE
Bug or a request? Handling of audiobooks

### ISSUE THREAD

**Issue by knaku** [casualsnek/onthespot#72]
**Describe the bug**
Tried to use it with an audiobook I have purchased, it seems like it doesn't have a handler for Audiobooks? It looks like it handles it like a Podcast and it fails when it doesn't find any episodes. This is the error message I got. 

﻿﻿Traceback (most recent call last):
  File "worker\utility.py", line 145, in run
  File "utils\spotify.py", line 354, in get_show_episodes
KeyError: 'items'

**To Reproduce**
1. Find an audiobook and copy link?
2. Paste link, search and download

**System Information (please complete the following information):**
 - OS: Windows 10
 - OnTheSpot Version: 0.5

**Comment by casualsnek** [comment]
Can you share the link to audiobook ?

**Comment by knaku** [comment]
Of course https://open.spotify.com/show/6Q0Jwgq8uKZY2xU1K3hAJ0

**Comment by casualsnek** [comment]
> Of course https://open.spotify.com/show/6Q0Jwgq8uKZY2xU1K3hAJ0

Thanks, but audio-book support may take some time to appear since I don't have audio-book feature on my region !
