### ISSUE TITLE
[BUG] Intallation fails in Ubuntu 22.04

### ISSUE THREAD

**Issue by ejgutierrez74** [casualsnek/onthespot#85]
**Describe the bug**
Follow the instructions to install from original web.

> 1.2. Launch with installing - from source
> 
> The requirements are the same as "Launching without installing" above.
> 
>     Download or Clone the repo git clone https://github.com/casualsnek/onthespot
>     Navigate to the onthespot directory cd onthespot
>     Install the package pip install .
>     Launch the application with onthespot_gui

**To Reproduce**
1. Follow instructions to install onthespot
2. Execute the instruction pip install . ( or sudo)
4. See error:
```
eduardo@MiPcLinux:~/Descargas/onthespot$ sudo pip install .
[sudo] contraseña para eduardo: 
Processing /home/eduardo/Descargas/onthespot
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
          req = REQUIREMENT.parseString(requirement_string)
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
          raise exc
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
          loc, tokens = self._parse( instring, 0 )
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
          loc, exprtokens = e._parse( instring, loc, doActions )
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
          raise ParseException(instring, loc, self.errmsg, self)
      pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 4), (line:1, col:5)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 1, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 807, in parse_config_files
          self._finalize_requires()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 534, in _finalize_requires
          self._move_install_requirements_markers()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 573, in _move_install_requirements_markers
          inst_reqs = list(pkg_resources.parse_requirements(spec_inst_reqs))
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3099, in parse_requirements
          yield Requirement(line)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3109, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
          raise InvalidRequirement(
      pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "':require'": Expected stringEnd
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Expected behavior**
onthespot is installed and you can execute onthespot-gui

**Screenshots**

**System Information (please complete the following information):**
 - OS: Ubuntu 22.04
 - OnTheSpot Version: 0.5

**Additional context**
Ubuntu 22.04 with latest updates.

**Comment by casualsnek** [comment]
it should be ```sudo pip install -r requirements.txt``` not ```pip install .```. Check if it fixes the build issue or not !

**Comment by casualsnek** [comment]
There was a small mistake in README.md about installing the built wheel package. I have updated it can you please check it and see if it fixes the issues:

Instead of ```pip install .```
run
```python 
python -m build
pip install ./dist/*.whl
```

**Comment by ejgutierrez74** [comment]
Should install build or include it in reqeriments.txt :+1: 

```
eduardo@MiPcLinux:/opt/onthespot$ python -m build
/usr/bin/python: No module named build
```

So i solved it:
`eduardo@MiPcLinux:/opt/onthespot$ pip install build`

Also i faced this problem:
```
Installing collected packages: onthespot
  WARNING: The script onthespot_gui is installed in '/home/eduardo/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed onthespot-0.5
```

So onthespot should be installed in one standard bin directory, in PATH like /usr/bin, /usr/local/bin

On a default Ubuntu desktop install $PATH is:

$ echo $PATH
/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Thanks for your work
